// src/app.ts
import express from "express";
import { toNodeHandler } from "better-auth/node";

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.0",
  "engineVersion": "ab56fe763f921d033a6c195e7ddeb3e255bdbb57",
  "activeProvider": "postgresql",
  "inlineSchema": '// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel User {\n  id            String     @id\n  name          String\n  email         String\n  emailVerified Boolean    @default(false)\n  role          Role       @default(STUDENT)\n  image         String?\n  phone         String?\n  status        UserStatus @default(ACTIVE)\n\n  createdAt DateTime  @default(now())\n  updatedAt DateTime  @updatedAt\n  sessions  Session[]\n  accounts  Account[]\n\n  tutor   TutorProfile?\n  booking Booking[]     @relation("StudentBookings")\n  review  Review[]\n\n  @@unique([email])\n  @@map("user")\n}\n\nmodel TutorProfile {\n  id          String  @id @default(uuid())\n  bio         String?\n  hourlyRate  Int\n  experience  Int\n  availablity Boolean @default(true)\n\n  categoryId String\n  category   Category @relation(fields: [categoryId], references: [id])\n\n  userId String @unique\n  user   User   @relation(fields: [userId], references: [id])\n\n  booking   Booking[] @relation("TutorBookings")\n  review    Review[]\n  createdAt DateTime  @default(now())\n  updatedAt DateTime  @updatedAt\n}\n\nmodel Category {\n  id   String @id @default(uuid())\n  name String @unique\n\n  tutor TutorProfile[]\n\n  @@map("category")\n}\n\nmodel Booking {\n  id        String        @id @default(uuid())\n  date      DateTime\n  status    BookingStatus @default(PENDING)\n  createdAt DateTime      @default(now())\n  updatedAt DateTime      @updatedAt\n\n  review Review?\n\n  tutorId String\n  tutor   TutorProfile @relation("TutorBookings", fields: [tutorId], references: [id])\n\n  userId String\n  user   User   @relation("StudentBookings", fields: [userId], references: [id])\n\n  @@map("booking")\n}\n\nmodel Review {\n  id      String  @id @default(uuid())\n  rating  Int\n  comment String?\n\n  tutorId String\n  tutor   TutorProfile @relation(fields: [tutorId], references: [id])\n\n  bookingId String  @unique\n  booking   Booking @relation(fields: [bookingId], references: [id])\n\n  userId String\n  user   User   @relation(fields: [userId], references: [id])\n\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n\n  @@map("review")\n}\n\nenum BookingStatus {\n  PENDING\n  CONFIRMED\n  COMPLETED\n  CANCELLED\n}\n\nenum Role {\n  STUDENT\n  TUTOR\n  ADMIN\n}\n\nenum UserStatus {\n  ACTIVE\n  BANED\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"role","kind":"enum","type":"Role"},{"name":"image","kind":"scalar","type":"String"},{"name":"phone","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"UserStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"TutorProfileToUser"},{"name":"booking","kind":"object","type":"Booking","relationName":"StudentBookings"},{"name":"review","kind":"object","type":"Review","relationName":"ReviewToUser"}],"dbName":"user"},"TutorProfile":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"bio","kind":"scalar","type":"String"},{"name":"hourlyRate","kind":"scalar","type":"Int"},{"name":"experience","kind":"scalar","type":"Int"},{"name":"availablity","kind":"scalar","type":"Boolean"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToTutorProfile"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"TutorProfileToUser"},{"name":"booking","kind":"object","type":"Booking","relationName":"TutorBookings"},{"name":"review","kind":"object","type":"Review","relationName":"ReviewToTutorProfile"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":null},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"CategoryToTutorProfile"}],"dbName":"category"},"Booking":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"date","kind":"scalar","type":"DateTime"},{"name":"status","kind":"enum","type":"BookingStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"review","kind":"object","type":"Review","relationName":"BookingToReview"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"TutorBookings"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"StudentBookings"}],"dbName":"booking"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"ReviewToTutorProfile"},{"name":"bookingId","kind":"scalar","type":"String"},{"name":"booking","kind":"object","type":"Booking","relationName":"BookingToReview"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"review"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","sessions","accounts","tutor","_count","category","booking","review","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","TutorProfile.findUnique","TutorProfile.findUniqueOrThrow","TutorProfile.findFirst","TutorProfile.findFirstOrThrow","TutorProfile.findMany","TutorProfile.createOne","TutorProfile.createMany","TutorProfile.createManyAndReturn","TutorProfile.updateOne","TutorProfile.updateMany","TutorProfile.updateManyAndReturn","TutorProfile.upsertOne","TutorProfile.deleteOne","TutorProfile.deleteMany","_avg","_sum","TutorProfile.groupBy","TutorProfile.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","Booking.groupBy","Booking.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","AND","OR","NOT","id","identifier","value","expiresAt","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","accountId","providerId","userId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","rating","comment","tutorId","bookingId","date","BookingStatus","status","name","every","some","none","bio","hourlyRate","experience","availablity","categoryId","email","emailVerified","Role","role","image","phone","UserStatus","is","isNot","connectOrCreate","upsert","disconnect","delete","connect","createMany","set","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "-QNIgAESBAAAiAIAIAUAAIkCACAGAACKAgAgCQAAiwIAIAoAAIwCACCTAQAAgwIAMJQBAAAjABCVAQAAgwIAMJYBAQAAAAGaAUAA4wEAIZsBQADjAQAhugEAAIcCywEiuwEBAOIBACHEAQEAAAABxQEgAIQCACHHAQAAhQLHASLIAQEAhgIAIckBAQCGAgAhAQAAAAEAIAwDAACRAgAgkwEAAJkCADCUAQAAAwAQlQEAAJkCADCWAQEA4gEAIZkBQADjAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhsQEBAOIBACGyAQEAhgIAIbMBAQCGAgAhAwMAAMMDACCyAQAAnwIAILMBAACfAgAgDAMAAJECACCTAQAAmQIAMJQBAAADABCVAQAAmQIAMJYBAQAAAAGZAUAA4wEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbEBAQAAAAGyAQEAhgIAIbMBAQCGAgAhAwAAAAMAIAEAAAQAMAIAAAUAIBEDAACRAgAgkwEAAJcCADCUAQAABwAQlQEAAJcCADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGnAQEA4gEAIagBAQDiAQAhqQEBAOIBACGqAQEAhgIAIasBAQCGAgAhrAEBAIYCACGtAUAAmAIAIa4BQACYAgAhrwEBAIYCACGwAQEAhgIAIQgDAADDAwAgqgEAAJ8CACCrAQAAnwIAIKwBAACfAgAgrQEAAJ8CACCuAQAAnwIAIK8BAACfAgAgsAEAAJ8CACARAwAAkQIAIJMBAACXAgAwlAEAAAcAEJUBAACXAgAwlgEBAAAAAZoBQADjAQAhmwFAAOMBACGnAQEA4gEAIagBAQDiAQAhqQEBAOIBACGqAQEAhgIAIasBAQCGAgAhrAEBAIYCACGtAUAAmAIAIa4BQACYAgAhrwEBAIYCACGwAQEAhgIAIQMAAAAHACABAAAIADACAAAJACAQAwAAkQIAIAgAAJYCACAJAACLAgAgCgAAjAIAIJMBAACVAgAwlAEAAAsAEJUBAACVAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG_AQEAhgIAIcABAgCOAgAhwQECAI4CACHCASAAhAIAIcMBAQDiAQAhAQAAAAsAIAUDAADDAwAgCAAAxQMAIAkAAMADACAKAADBAwAgvwEAAJ8CACAQAwAAkQIAIAgAAJYCACAJAACLAgAgCgAAjAIAIJMBAACVAgAwlAEAAAsAEJUBAACVAgAwlgEBAAAAAZoBQADjAQAhmwFAAOMBACGpAQEAAAABvwEBAIYCACHAAQIAjgIAIcEBAgCOAgAhwgEgAIQCACHDAQEA4gEAIQMAAAALACABAAANADACAAAOACABAAAACwAgDQMAAJECACAGAACPAgAgCgAAlAIAIJMBAACSAgAwlAEAABEAEJUBAACSAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG2AQEA4gEAIbgBQADjAQAhugEAAJMCugEiAwMAAMMDACAGAAC_AwAgCgAAxAMAIA0DAACRAgAgBgAAjwIAIAoAAJQCACCTAQAAkgIAMJQBAAARABCVAQAAkgIAMJYBAQAAAAGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG2AQEA4gEAIbgBQADjAQAhugEAAJMCugEiAwAAABEAIAEAABIAMAIAABMAIA4DAACRAgAgBgAAjwIAIAkAAJACACCTAQAAjQIAMJQBAAAVABCVAQAAjQIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhtAECAI4CACG1AQEAhgIAIbYBAQDiAQAhtwEBAOIBACEBAAAAFQAgBAMAAMMDACAGAAC_AwAgCQAAwgMAILUBAACfAgAgDgMAAJECACAGAACPAgAgCQAAkAIAIJMBAACNAgAwlAEAABUAEJUBAACNAgAwlgEBAAAAAZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbQBAgCOAgAhtQEBAIYCACG2AQEA4gEAIbcBAQAAAAEDAAAAFQAgAQAAFwAwAgAAGAAgAQAAABEAIAEAAAAVACADAAAAEQAgAQAAEgAwAgAAEwAgAwAAABUAIAEAABcAMAIAABgAIAEAAAADACABAAAABwAgAQAAABEAIAEAAAAVACABAAAAAQAgEgQAAIgCACAFAACJAgAgBgAAigIAIAkAAIsCACAKAACMAgAgkwEAAIMCADCUAQAAIwAQlQEAAIMCADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACG6AQAAhwLLASK7AQEA4gEAIcQBAQDiAQAhxQEgAIQCACHHAQAAhQLHASLIAQEAhgIAIckBAQCGAgAhBwQAAL0DACAFAAC-AwAgBgAAvwMAIAkAAMADACAKAADBAwAgyAEAAJ8CACDJAQAAnwIAIAMAAAAjACABAAAkADACAAABACADAAAAIwAgAQAAJAAwAgAAAQAgAwAAACMAIAEAACQAMAIAAAEAIA8EAAC4AwAgBQAAuQMAIAYAALoDACAJAAC7AwAgCgAAvAMAIJYBAQAAAAGaAUAAAAABmwFAAAAAAboBAAAAywECuwEBAAAAAcQBAQAAAAHFASAAAAABxwEAAADHAQLIAQEAAAAByQEBAAAAAQEQAAAoACAKlgEBAAAAAZoBQAAAAAGbAUAAAAABugEAAADLAQK7AQEAAAABxAEBAAAAAcUBIAAAAAHHAQAAAMcBAsgBAQAAAAHJAQEAAAABARAAACoAMAEQAAAqADAPBAAAhAMAIAUAAIUDACAGAACGAwAgCQAAhwMAIAoAAIgDACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG6AQAAgwPLASK7AQEAnQIAIcQBAQCdAgAhxQEgANUCACHHAQAAggPHASLIAQEAowIAIckBAQCjAgAhAgAAAAEAIBAAAC0AIAqWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG6AQAAgwPLASK7AQEAnQIAIcQBAQCdAgAhxQEgANUCACHHAQAAggPHASLIAQEAowIAIckBAQCjAgAhAgAAACMAIBAAAC8AIAIAAAAjACAQAAAvACADAAAAAQAgFwAAKAAgGAAALQAgAQAAAAEAIAEAAAAjACAFBwAA_wIAIB0AAIEDACAeAACAAwAgyAEAAJ8CACDJAQAAnwIAIA2TAQAA_AEAMJQBAAA2ABCVAQAA_AEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIboBAAD-AcsBIrsBAQDaAQAhxAEBANoBACHFASAA-QEAIccBAAD9AccBIsgBAQDlAQAhyQEBAOUBACEDAAAAIwAgAQAANQAwHAAANgAgAwAAACMAIAEAACQAMAIAAAEAIAEAAAAOACABAAAADgAgAwAAAAsAIAEAAA0AMAIAAA4AIAMAAAALACABAAANADACAAAOACADAAAACwAgAQAADQAwAgAADgAgDQMAAPMCACAIAAD-AgAgCQAA9AIAIAoAAPUCACCWAQEAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABvwEBAAAAAcABAgAAAAHBAQIAAAABwgEgAAAAAcMBAQAAAAEBEAAAPgAgCZYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG_AQEAAAABwAECAAAAAcEBAgAAAAHCASAAAAABwwEBAAAAAQEQAABAADABEAAAQAAwDQMAANcCACAIAAD9AgAgCQAA2AIAIAoAANkCACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIb8BAQCjAgAhwAECALECACHBAQIAsQIAIcIBIADVAgAhwwEBAJ0CACECAAAADgAgEAAAQwAgCZYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhvwEBAKMCACHAAQIAsQIAIcEBAgCxAgAhwgEgANUCACHDAQEAnQIAIQIAAAALACAQAABFACACAAAACwAgEAAARQAgAwAAAA4AIBcAAD4AIBgAAEMAIAEAAAAOACABAAAACwAgBgcAAPgCACAdAAD7AgAgHgAA-gIAIC8AAPkCACAwAAD8AgAgvwEAAJ8CACAMkwEAAPgBADCUAQAATAAQlQEAAPgBADCWAQEA2gEAIZoBQADbAQAhmwFAANsBACGpAQEA2gEAIb8BAQDlAQAhwAECAO4BACHBAQIA7gEAIcIBIAD5AQAhwwEBANoBACEDAAAACwAgAQAASwAwHAAATAAgAwAAAAsAIAEAAA0AMAIAAA4AIAYGAAD3AQAgkwEAAPYBADCUAQAAUgAQlQEAAPYBADCWAQEAAAABuwEBAAAAAQEAAABPACABAAAATwAgBgYAAPcBACCTAQAA9gEAMJQBAABSABCVAQAA9gEAMJYBAQDiAQAhuwEBAOIBACEBBgAA9wIAIAMAAABSACABAABTADACAABPACADAAAAUgAgAQAAUwAwAgAATwAgAwAAAFIAIAEAAFMAMAIAAE8AIAMGAAD2AgAglgEBAAAAAbsBAQAAAAEBEAAAVwAgApYBAQAAAAG7AQEAAAABARAAAFkAMAEQAABZADADBgAAygIAIJYBAQCdAgAhuwEBAJ0CACECAAAATwAgEAAAXAAgApYBAQCdAgAhuwEBAJ0CACECAAAAUgAgEAAAXgAgAgAAAFIAIBAAAF4AIAMAAABPACAXAABXACAYAABcACABAAAATwAgAQAAAFIAIAMHAADHAgAgHQAAyQIAIB4AAMgCACAFkwEAAPUBADCUAQAAZQAQlQEAAPUBADCWAQEA2gEAIbsBAQDaAQAhAwAAAFIAIAEAAGQAMBwAAGUAIAMAAABSACABAABTADACAABPACABAAAAEwAgAQAAABMAIAMAAAARACABAAASADACAAATACADAAAAEQAgAQAAEgAwAgAAEwAgAwAAABEAIAEAABIAMAIAABMAIAoDAADGAgAgBgAAxQIAIAoAAMQCACCWAQEAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABtgEBAAAAAbgBQAAAAAG6AQAAALoBAgEQAABtACAHlgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbYBAQAAAAG4AUAAAAABugEAAAC6AQIBEAAAbwAwARAAAG8AMAoDAAC-AgAgBgAAvQIAIAoAALwCACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbYBAQCdAgAhuAFAAJ4CACG6AQAAuwK6ASICAAAAEwAgEAAAcgAgB5YBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhtgEBAJ0CACG4AUAAngIAIboBAAC7AroBIgIAAAARACAQAAB0ACACAAAAEQAgEAAAdAAgAwAAABMAIBcAAG0AIBgAAHIAIAEAAAATACABAAAAEQAgAwcAALgCACAdAAC6AgAgHgAAuQIAIAqTAQAA8QEAMJQBAAB7ABCVAQAA8QEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIakBAQDaAQAhtgEBANoBACG4AUAA2wEAIboBAADyAboBIgMAAAARACABAAB6ADAcAAB7ACADAAAAEQAgAQAAEgAwAgAAEwAgAQAAABgAIAEAAAAYACADAAAAFQAgAQAAFwAwAgAAGAAgAwAAABUAIAEAABcAMAIAABgAIAMAAAAVACABAAAXADACAAAYACALAwAAtwIAIAYAALUCACAJAAC2AgAglgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbQBAgAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAEBEAAAgwEAIAiWAQEAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABtAECAAAAAbUBAQAAAAG2AQEAAAABtwEBAAAAAQEQAACFAQAwARAAAIUBADALAwAAtAIAIAYAALICACAJAACzAgAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhqQEBAJ0CACG0AQIAsQIAIbUBAQCjAgAhtgEBAJ0CACG3AQEAnQIAIQIAAAAYACAQAACIAQAgCJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhtAECALECACG1AQEAowIAIbYBAQCdAgAhtwEBAJ0CACECAAAAFQAgEAAAigEAIAIAAAAVACAQAACKAQAgAwAAABgAIBcAAIMBACAYAACIAQAgAQAAABgAIAEAAAAVACAGBwAArAIAIB0AAK8CACAeAACuAgAgLwAArQIAIDAAALACACC1AQAAnwIAIAuTAQAA7QEAMJQBAACRAQAQlQEAAO0BADCWAQEA2gEAIZoBQADbAQAhmwFAANsBACGpAQEA2gEAIbQBAgDuAQAhtQEBAOUBACG2AQEA2gEAIbcBAQDaAQAhAwAAABUAIAEAAJABADAcAACRAQAgAwAAABUAIAEAABcAMAIAABgAIAEAAAAFACABAAAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACADAAAAAwAgAQAABAAwAgAABQAgCQMAAKsCACCWAQEAAAABmQFAAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbEBAQAAAAGyAQEAAAABswEBAAAAAQEQAACZAQAgCJYBAQAAAAGZAUAAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABsQEBAAAAAbIBAQAAAAGzAQEAAAABARAAAJsBADABEAAAmwEAMAkDAACqAgAglgEBAJ0CACGZAUAAngIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbEBAQCdAgAhsgEBAKMCACGzAQEAowIAIQIAAAAFACAQAACeAQAgCJYBAQCdAgAhmQFAAJ4CACGaAUAAngIAIZsBQACeAgAhqQEBAJ0CACGxAQEAnQIAIbIBAQCjAgAhswEBAKMCACECAAAAAwAgEAAAoAEAIAIAAAADACAQAACgAQAgAwAAAAUAIBcAAJkBACAYAACeAQAgAQAAAAUAIAEAAAADACAFBwAApwIAIB0AAKkCACAeAACoAgAgsgEAAJ8CACCzAQAAnwIAIAuTAQAA7AEAMJQBAACnAQAQlQEAAOwBADCWAQEA2gEAIZkBQADbAQAhmgFAANsBACGbAUAA2wEAIakBAQDaAQAhsQEBANoBACGyAQEA5QEAIbMBAQDlAQAhAwAAAAMAIAEAAKYBADAcAACnAQAgAwAAAAMAIAEAAAQAMAIAAAUAIAEAAAAJACABAAAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAHACABAAAIADACAAAJACADAAAABwAgAQAACAAwAgAACQAgDgMAAKYCACCWAQEAAAABmgFAAAAAAZsBQAAAAAGnAQEAAAABqAEBAAAAAakBAQAAAAGqAQEAAAABqwEBAAAAAawBAQAAAAGtAUAAAAABrgFAAAAAAa8BAQAAAAGwAQEAAAABARAAAK8BACANlgEBAAAAAZoBQAAAAAGbAUAAAAABpwEBAAAAAagBAQAAAAGpAQEAAAABqgEBAAAAAasBAQAAAAGsAQEAAAABrQFAAAAAAa4BQAAAAAGvAQEAAAABsAEBAAAAAQEQAACxAQAwARAAALEBADAOAwAApQIAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIacBAQCdAgAhqAEBAJ0CACGpAQEAnQIAIaoBAQCjAgAhqwEBAKMCACGsAQEAowIAIa0BQACkAgAhrgFAAKQCACGvAQEAowIAIbABAQCjAgAhAgAAAAkAIBAAALQBACANlgEBAJ0CACGaAUAAngIAIZsBQACeAgAhpwEBAJ0CACGoAQEAnQIAIakBAQCdAgAhqgEBAKMCACGrAQEAowIAIawBAQCjAgAhrQFAAKQCACGuAUAApAIAIa8BAQCjAgAhsAEBAKMCACECAAAABwAgEAAAtgEAIAIAAAAHACAQAAC2AQAgAwAAAAkAIBcAAK8BACAYAAC0AQAgAQAAAAkAIAEAAAAHACAKBwAAoAIAIB0AAKICACAeAAChAgAgqgEAAJ8CACCrAQAAnwIAIKwBAACfAgAgrQEAAJ8CACCuAQAAnwIAIK8BAACfAgAgsAEAAJ8CACAQkwEAAOQBADCUAQAAvQEAEJUBAADkAQAwlgEBANoBACGaAUAA2wEAIZsBQADbAQAhpwEBANoBACGoAQEA2gEAIakBAQDaAQAhqgEBAOUBACGrAQEA5QEAIawBAQDlAQAhrQFAAOYBACGuAUAA5gEAIa8BAQDlAQAhsAEBAOUBACEDAAAABwAgAQAAvAEAMBwAAL0BACADAAAABwAgAQAACAAwAgAACQAgCZMBAADhAQAwlAEAAMMBABCVAQAA4QEAMJYBAQAAAAGXAQEA4gEAIZgBAQDiAQAhmQFAAOMBACGaAUAA4wEAIZsBQADjAQAhAQAAAMABACABAAAAwAEAIAmTAQAA4QEAMJQBAADDAQAQlQEAAOEBADCWAQEA4gEAIZcBAQDiAQAhmAEBAOIBACGZAUAA4wEAIZoBQADjAQAhmwFAAOMBACEAAwAAAMMBACABAADEAQAwAgAAwAEAIAMAAADDAQAgAQAAxAEAMAIAAMABACADAAAAwwEAIAEAAMQBADACAADAAQAgBpYBAQAAAAGXAQEAAAABmAEBAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAQEQAADIAQAgBpYBAQAAAAGXAQEAAAABmAEBAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAQEQAADKAQAwARAAAMoBADAGlgEBAJ0CACGXAQEAnQIAIZgBAQCdAgAhmQFAAJ4CACGaAUAAngIAIZsBQACeAgAhAgAAAMABACAQAADNAQAgBpYBAQCdAgAhlwEBAJ0CACGYAQEAnQIAIZkBQACeAgAhmgFAAJ4CACGbAUAAngIAIQIAAADDAQAgEAAAzwEAIAIAAADDAQAgEAAAzwEAIAMAAADAAQAgFwAAyAEAIBgAAM0BACABAAAAwAEAIAEAAADDAQAgAwcAAJoCACAdAACcAgAgHgAAmwIAIAmTAQAA2QEAMJQBAADWAQAQlQEAANkBADCWAQEA2gEAIZcBAQDaAQAhmAEBANoBACGZAUAA2wEAIZoBQADbAQAhmwFAANsBACEDAAAAwwEAIAEAANUBADAcAADWAQAgAwAAAMMBACABAADEAQAwAgAAwAEAIAmTAQAA2QEAMJQBAADWAQAQlQEAANkBADCWAQEA2gEAIZcBAQDaAQAhmAEBANoBACGZAUAA2wEAIZoBQADbAQAhmwFAANsBACEOBwAA3QEAIB0AAOABACAeAADgAQAgnAEBAAAAAZ0BAQAAAASeAQEAAAAEnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBAQDfAQAhpAEBAAAAAaUBAQAAAAGmAQEAAAABCwcAAN0BACAdAADeAQAgHgAA3gEAIJwBQAAAAAGdAUAAAAAEngFAAAAABJ8BQAAAAAGgAUAAAAABoQFAAAAAAaIBQAAAAAGjAUAA3AEAIQsHAADdAQAgHQAA3gEAIB4AAN4BACCcAUAAAAABnQFAAAAABJ4BQAAAAASfAUAAAAABoAFAAAAAAaEBQAAAAAGiAUAAAAABowFAANwBACEInAECAAAAAZ0BAgAAAASeAQIAAAAEnwECAAAAAaABAgAAAAGhAQIAAAABogECAAAAAaMBAgDdAQAhCJwBQAAAAAGdAUAAAAAEngFAAAAABJ8BQAAAAAGgAUAAAAABoQFAAAAAAaIBQAAAAAGjAUAA3gEAIQ4HAADdAQAgHQAA4AEAIB4AAOABACCcAQEAAAABnQEBAAAABJ4BAQAAAASfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEBAN8BACGkAQEAAAABpQEBAAAAAaYBAQAAAAELnAEBAAAAAZ0BAQAAAASeAQEAAAAEnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBAQDgAQAhpAEBAAAAAaUBAQAAAAGmAQEAAAABCZMBAADhAQAwlAEAAMMBABCVAQAA4QEAMJYBAQDiAQAhlwEBAOIBACGYAQEA4gEAIZkBQADjAQAhmgFAAOMBACGbAUAA4wEAIQucAQEAAAABnQEBAAAABJ4BAQAAAASfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEBAOABACGkAQEAAAABpQEBAAAAAaYBAQAAAAEInAFAAAAAAZ0BQAAAAASeAUAAAAAEnwFAAAAAAaABQAAAAAGhAUAAAAABogFAAAAAAaMBQADeAQAhEJMBAADkAQAwlAEAAL0BABCVAQAA5AEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIacBAQDaAQAhqAEBANoBACGpAQEA2gEAIaoBAQDlAQAhqwEBAOUBACGsAQEA5QEAIa0BQADmAQAhrgFAAOYBACGvAQEA5QEAIbABAQDlAQAhDgcAAOgBACAdAADrAQAgHgAA6wEAIJwBAQAAAAGdAQEAAAAFngEBAAAABZ8BAQAAAAGgAQEAAAABoQEBAAAAAaIBAQAAAAGjAQEA6gEAIaQBAQAAAAGlAQEAAAABpgEBAAAAAQsHAADoAQAgHQAA6QEAIB4AAOkBACCcAUAAAAABnQFAAAAABZ4BQAAAAAWfAUAAAAABoAFAAAAAAaEBQAAAAAGiAUAAAAABowFAAOcBACELBwAA6AEAIB0AAOkBACAeAADpAQAgnAFAAAAAAZ0BQAAAAAWeAUAAAAAFnwFAAAAAAaABQAAAAAGhAUAAAAABogFAAAAAAaMBQADnAQAhCJwBAgAAAAGdAQIAAAAFngECAAAABZ8BAgAAAAGgAQIAAAABoQECAAAAAaIBAgAAAAGjAQIA6AEAIQicAUAAAAABnQFAAAAABZ4BQAAAAAWfAUAAAAABoAFAAAAAAaEBQAAAAAGiAUAAAAABowFAAOkBACEOBwAA6AEAIB0AAOsBACAeAADrAQAgnAEBAAAAAZ0BAQAAAAWeAQEAAAAFnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBAQDqAQAhpAEBAAAAAaUBAQAAAAGmAQEAAAABC5wBAQAAAAGdAQEAAAAFngEBAAAABZ8BAQAAAAGgAQEAAAABoQEBAAAAAaIBAQAAAAGjAQEA6wEAIaQBAQAAAAGlAQEAAAABpgEBAAAAAQuTAQAA7AEAMJQBAACnAQAQlQEAAOwBADCWAQEA2gEAIZkBQADbAQAhmgFAANsBACGbAUAA2wEAIakBAQDaAQAhsQEBANoBACGyAQEA5QEAIbMBAQDlAQAhC5MBAADtAQAwlAEAAJEBABCVAQAA7QEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIakBAQDaAQAhtAECAO4BACG1AQEA5QEAIbYBAQDaAQAhtwEBANoBACENBwAA3QEAIB0AAN0BACAeAADdAQAgLwAA8AEAIDAAAN0BACCcAQIAAAABnQECAAAABJ4BAgAAAASfAQIAAAABoAECAAAAAaEBAgAAAAGiAQIAAAABowECAO8BACENBwAA3QEAIB0AAN0BACAeAADdAQAgLwAA8AEAIDAAAN0BACCcAQIAAAABnQECAAAABJ4BAgAAAASfAQIAAAABoAECAAAAAaEBAgAAAAGiAQIAAAABowECAO8BACEInAEIAAAAAZ0BCAAAAASeAQgAAAAEnwEIAAAAAaABCAAAAAGhAQgAAAABogEIAAAAAaMBCADwAQAhCpMBAADxAQAwlAEAAHsAEJUBAADxAQAwlgEBANoBACGaAUAA2wEAIZsBQADbAQAhqQEBANoBACG2AQEA2gEAIbgBQADbAQAhugEAAPIBugEiBwcAAN0BACAdAAD0AQAgHgAA9AEAIJwBAAAAugECnQEAAAC6AQieAQAAALoBCKMBAADzAboBIgcHAADdAQAgHQAA9AEAIB4AAPQBACCcAQAAALoBAp0BAAAAugEIngEAAAC6AQijAQAA8wG6ASIEnAEAAAC6AQKdAQAAALoBCJ4BAAAAugEIowEAAPQBugEiBZMBAAD1AQAwlAEAAGUAEJUBAAD1AQAwlgEBANoBACG7AQEA2gEAIQYGAAD3AQAgkwEAAPYBADCUAQAAUgAQlQEAAPYBADCWAQEA4gEAIbsBAQDiAQAhA7wBAAALACC9AQAACwAgvgEAAAsAIAyTAQAA-AEAMJQBAABMABCVAQAA-AEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIakBAQDaAQAhvwEBAOUBACHAAQIA7gEAIcEBAgDuAQAhwgEgAPkBACHDAQEA2gEAIQUHAADdAQAgHQAA-wEAIB4AAPsBACCcASAAAAABowEgAPoBACEFBwAA3QEAIB0AAPsBACAeAAD7AQAgnAEgAAAAAaMBIAD6AQAhApwBIAAAAAGjASAA-wEAIQ2TAQAA_AEAMJQBAAA2ABCVAQAA_AEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIboBAAD-AcsBIrsBAQDaAQAhxAEBANoBACHFASAA-QEAIccBAAD9AccBIsgBAQDlAQAhyQEBAOUBACEHBwAA3QEAIB0AAIICACAeAACCAgAgnAEAAADHAQKdAQAAAMcBCJ4BAAAAxwEIowEAAIECxwEiBwcAAN0BACAdAACAAgAgHgAAgAIAIJwBAAAAywECnQEAAADLAQieAQAAAMsBCKMBAAD_AcsBIgcHAADdAQAgHQAAgAIAIB4AAIACACCcAQAAAMsBAp0BAAAAywEIngEAAADLAQijAQAA_wHLASIEnAEAAADLAQKdAQAAAMsBCJ4BAAAAywEIowEAAIACywEiBwcAAN0BACAdAACCAgAgHgAAggIAIJwBAAAAxwECnQEAAADHAQieAQAAAMcBCKMBAACBAscBIgScAQAAAMcBAp0BAAAAxwEIngEAAADHAQijAQAAggLHASISBAAAiAIAIAUAAIkCACAGAACKAgAgCQAAiwIAIAoAAIwCACCTAQAAgwIAMJQBAAAjABCVAQAAgwIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIboBAACHAssBIrsBAQDiAQAhxAEBAOIBACHFASAAhAIAIccBAACFAscBIsgBAQCGAgAhyQEBAIYCACECnAEgAAAAAaMBIAD7AQAhBJwBAAAAxwECnQEAAADHAQieAQAAAMcBCKMBAACCAscBIgucAQEAAAABnQEBAAAABZ4BAQAAAAWfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEBAOsBACGkAQEAAAABpQEBAAAAAaYBAQAAAAEEnAEAAADLAQKdAQAAAMsBCJ4BAAAAywEIowEAAIACywEiA7wBAAADACC9AQAAAwAgvgEAAAMAIAO8AQAABwAgvQEAAAcAIL4BAAAHACASAwAAkQIAIAgAAJYCACAJAACLAgAgCgAAjAIAIJMBAACVAgAwlAEAAAsAEJUBAACVAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG_AQEAhgIAIcABAgCOAgAhwQECAI4CACHCASAAhAIAIcMBAQDiAQAhywEAAAsAIMwBAAALACADvAEAABEAIL0BAAARACC-AQAAEQAgA7wBAAAVACC9AQAAFQAgvgEAABUAIA4DAACRAgAgBgAAjwIAIAkAAJACACCTAQAAjQIAMJQBAAAVABCVAQAAjQIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhtAECAI4CACG1AQEAhgIAIbYBAQDiAQAhtwEBAOIBACEInAECAAAAAZ0BAgAAAASeAQIAAAAEnwECAAAAAaABAgAAAAGhAQIAAAABogECAAAAAaMBAgDdAQAhEgMAAJECACAIAACWAgAgCQAAiwIAIAoAAIwCACCTAQAAlQIAMJQBAAALABCVAQAAlQIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhvwEBAIYCACHAAQIAjgIAIcEBAgCOAgAhwgEgAIQCACHDAQEA4gEAIcsBAAALACDMAQAACwAgDwMAAJECACAGAACPAgAgCgAAlAIAIJMBAACSAgAwlAEAABEAEJUBAACSAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG2AQEA4gEAIbgBQADjAQAhugEAAJMCugEiywEAABEAIMwBAAARACAUBAAAiAIAIAUAAIkCACAGAACKAgAgCQAAiwIAIAoAAIwCACCTAQAAgwIAMJQBAAAjABCVAQAAgwIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIboBAACHAssBIrsBAQDiAQAhxAEBAOIBACHFASAAhAIAIccBAACFAscBIsgBAQCGAgAhyQEBAIYCACHLAQAAIwAgzAEAACMAIA0DAACRAgAgBgAAjwIAIAoAAJQCACCTAQAAkgIAMJQBAAARABCVAQAAkgIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhtgEBAOIBACG4AUAA4wEAIboBAACTAroBIgScAQAAALoBAp0BAAAAugEIngEAAAC6AQijAQAA9AG6ASIQAwAAkQIAIAYAAI8CACAJAACQAgAgkwEAAI0CADCUAQAAFQAQlQEAAI0CADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbQBAgCOAgAhtQEBAIYCACG2AQEA4gEAIbcBAQDiAQAhywEAABUAIMwBAAAVACAQAwAAkQIAIAgAAJYCACAJAACLAgAgCgAAjAIAIJMBAACVAgAwlAEAAAsAEJUBAACVAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG_AQEAhgIAIcABAgCOAgAhwQECAI4CACHCASAAhAIAIcMBAQDiAQAhCAYAAPcBACCTAQAA9gEAMJQBAABSABCVAQAA9gEAMJYBAQDiAQAhuwEBAOIBACHLAQAAUgAgzAEAAFIAIBEDAACRAgAgkwEAAJcCADCUAQAABwAQlQEAAJcCADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGnAQEA4gEAIagBAQDiAQAhqQEBAOIBACGqAQEAhgIAIasBAQCGAgAhrAEBAIYCACGtAUAAmAIAIa4BQACYAgAhrwEBAIYCACGwAQEAhgIAIQicAUAAAAABnQFAAAAABZ4BQAAAAAWfAUAAAAABoAFAAAAAAaEBQAAAAAGiAUAAAAABowFAAOkBACEMAwAAkQIAIJMBAACZAgAwlAEAAAMAEJUBAACZAgAwlgEBAOIBACGZAUAA4wEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbEBAQDiAQAhsgEBAIYCACGzAQEAhgIAIQAAAAHTAQEAAAABAdMBQAAAAAEAAAAAAdMBAQAAAAEB0wFAAAAAAQUXAAD1AwAgGAAA-AMAIM0BAAD2AwAgzgEAAPcDACDRAQAAAQAgAxcAAPUDACDNAQAA9gMAINEBAAABACAAAAAFFwAA8AMAIBgAAPMDACDNAQAA8QMAIM4BAADyAwAg0QEAAAEAIAMXAADwAwAgzQEAAPEDACDRAQAAAQAgAAAAAAAF0wECAAAAAdYBAgAAAAHXAQIAAAAB2AECAAAAAdkBAgAAAAEFFwAA5QMAIBgAAO4DACDNAQAA5gMAIM4BAADtAwAg0QEAAA4AIAUXAADjAwAgGAAA6wMAIM0BAADkAwAgzgEAAOoDACDRAQAAEwAgBRcAAOEDACAYAADoAwAgzQEAAOIDACDOAQAA5wMAINEBAAABACADFwAA5QMAIM0BAADmAwAg0QEAAA4AIAMXAADjAwAgzQEAAOQDACDRAQAAEwAgAxcAAOEDACDNAQAA4gMAINEBAAABACAAAAAB0wEAAAC6AQIHFwAAvwIAIBgAAMICACDNAQAAwAIAIM4BAADBAgAgzwEAABUAINABAAAVACDRAQAAGAAgBRcAANkDACAYAADfAwAgzQEAANoDACDOAQAA3gMAINEBAAAOACAFFwAA1wMAIBgAANwDACDNAQAA2AMAIM4BAADbAwAg0QEAAAEAIAkDAAC3AgAgBgAAtQIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG0AQIAAAABtQEBAAAAAbYBAQAAAAECAAAAGAAgFwAAvwIAIAMAAAAVACAXAAC_AgAgGAAAwwIAIAsAAAAVACADAAC0AgAgBgAAsgIAIBAAAMMCACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbQBAgCxAgAhtQEBAKMCACG2AQEAnQIAIQkDAAC0AgAgBgAAsgIAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhtAECALECACG1AQEAowIAIbYBAQCdAgAhAxcAAL8CACDNAQAAwAIAINEBAAAYACADFwAA2QMAIM0BAADaAwAg0QEAAA4AIAMXAADXAwAgzQEAANgDACDRAQAAAQAgAAAACxcAAMsCADAYAADQAgAwzQEAAMwCADDOAQAAzQIAMM8BAADPAgAw0AEAAM8CADDRAQAAzwIAMNIBAADOAgAg0wEAAM8CADDUAQAA0QIAMNUBAADSAgAwCwMAAPMCACAJAAD0AgAgCgAA9QIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG_AQEAAAABwAECAAAAAcEBAgAAAAHCASAAAAABAgAAAA4AIBcAAPICACADAAAADgAgFwAA8gIAIBgAANYCACABEAAA1gMAMBADAACRAgAgCAAAlgIAIAkAAIsCACAKAACMAgAgkwEAAJUCADCUAQAACwAQlQEAAJUCADCWAQEAAAABmgFAAOMBACGbAUAA4wEAIakBAQAAAAG_AQEAhgIAIcABAgCOAgAhwQECAI4CACHCASAAhAIAIcMBAQDiAQAhAgAAAA4AIBAAANYCACACAAAA0wIAIBAAANQCACAMkwEAANICADCUAQAA0wIAEJUBAADSAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG_AQEAhgIAIcABAgCOAgAhwQECAI4CACHCASAAhAIAIcMBAQDiAQAhDJMBAADSAgAwlAEAANMCABCVAQAA0gIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhvwEBAIYCACHAAQIAjgIAIcEBAgCOAgAhwgEgAIQCACHDAQEA4gEAIQiWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIb8BAQCjAgAhwAECALECACHBAQIAsQIAIcIBIADVAgAhAdMBIAAAAAELAwAA1wIAIAkAANgCACAKAADZAgAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhqQEBAJ0CACG_AQEAowIAIcABAgCxAgAhwQECALECACHCASAA1QIAIQUXAADPAwAgGAAA1AMAIM0BAADQAwAgzgEAANMDACDRAQAAAQAgCxcAAOYCADAYAADrAgAwzQEAAOcCADDOAQAA6AIAMM8BAADqAgAw0AEAAOoCADDRAQAA6gIAMNIBAADpAgAg0wEAAOoCADDUAQAA7AIAMNUBAADtAgAwCxcAANoCADAYAADfAgAwzQEAANsCADDOAQAA3AIAMM8BAADeAgAw0AEAAN4CADDRAQAA3gIAMNIBAADdAgAg0wEAAN4CADDUAQAA4AIAMNUBAADhAgAwCQMAALcCACAJAAC2AgAglgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbQBAgAAAAG1AQEAAAABtwEBAAAAAQIAAAAYACAXAADlAgAgAwAAABgAIBcAAOUCACAYAADkAgAgARAAANIDADAOAwAAkQIAIAYAAI8CACAJAACQAgAgkwEAAI0CADCUAQAAFQAQlQEAAI0CADCWAQEAAAABmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhtAECAI4CACG1AQEAhgIAIbYBAQDiAQAhtwEBAAAAAQIAAAAYACAQAADkAgAgAgAAAOICACAQAADjAgAgC5MBAADhAgAwlAEAAOICABCVAQAA4QIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhtAECAI4CACG1AQEAhgIAIbYBAQDiAQAhtwEBAOIBACELkwEAAOECADCUAQAA4gIAEJUBAADhAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG0AQIAjgIAIbUBAQCGAgAhtgEBAOIBACG3AQEA4gEAIQeWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbQBAgCxAgAhtQEBAKMCACG3AQEAnQIAIQkDAAC0AgAgCQAAswIAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhtAECALECACG1AQEAowIAIbcBAQCdAgAhCQMAALcCACAJAAC2AgAglgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbQBAgAAAAG1AQEAAAABtwEBAAAAAQgDAADGAgAgCgAAxAIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG4AUAAAAABugEAAAC6AQICAAAAEwAgFwAA8QIAIAMAAAATACAXAADxAgAgGAAA8AIAIAEQAADRAwAwDQMAAJECACAGAACPAgAgCgAAlAIAIJMBAACSAgAwlAEAABEAEJUBAACSAgAwlgEBAAAAAZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbYBAQDiAQAhuAFAAOMBACG6AQAAkwK6ASICAAAAEwAgEAAA8AIAIAIAAADuAgAgEAAA7wIAIAqTAQAA7QIAMJQBAADuAgAQlQEAAO0CADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbYBAQDiAQAhuAFAAOMBACG6AQAAkwK6ASIKkwEAAO0CADCUAQAA7gIAEJUBAADtAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG2AQEA4gEAIbgBQADjAQAhugEAAJMCugEiBpYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhuAFAAJ4CACG6AQAAuwK6ASIIAwAAvgIAIAoAALwCACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbgBQACeAgAhugEAALsCugEiCAMAAMYCACAKAADEAgAglgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbgBQAAAAAG6AQAAALoBAgsDAADzAgAgCQAA9AIAIAoAAPUCACCWAQEAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABvwEBAAAAAcABAgAAAAHBAQIAAAABwgEgAAAAAQMXAADPAwAgzQEAANADACDRAQAAAQAgBBcAAOYCADDNAQAA5wIAMNEBAADqAgAw0gEAAOkCACAEFwAA2gIAMM0BAADbAgAw0QEAAN4CADDSAQAA3QIAIAQXAADLAgAwzQEAAMwCADDRAQAAzwIAMNIBAADOAgAgAAAAAAAABRcAAMoDACAYAADNAwAgzQEAAMsDACDOAQAAzAMAINEBAABPACADFwAAygMAIM0BAADLAwAg0QEAAE8AIAAAAAHTAQAAAMcBAgHTAQAAAMsBAgsXAACsAwAwGAAAsQMAMM0BAACtAwAwzgEAAK4DADDPAQAAsAMAMNABAACwAwAw0QEAALADADDSAQAArwMAINMBAACwAwAw1AEAALIDADDVAQAAswMAMAsXAACgAwAwGAAApQMAMM0BAAChAwAwzgEAAKIDADDPAQAApAMAMNABAACkAwAw0QEAAKQDADDSAQAAowMAINMBAACkAwAw1AEAAKYDADDVAQAApwMAMAcXAACbAwAgGAAAngMAIM0BAACcAwAgzgEAAJ0DACDPAQAACwAg0AEAAAsAINEBAAAOACALFwAAkgMAMBgAAJYDADDNAQAAkwMAMM4BAACUAwAwzwEAAOoCADDQAQAA6gIAMNEBAADqAgAw0gEAAJUDACDTAQAA6gIAMNQBAACXAwAw1QEAAO0CADALFwAAiQMAMBgAAI0DADDNAQAAigMAMM4BAACLAwAwzwEAAN4CADDQAQAA3gIAMNEBAADeAgAw0gEAAIwDACDTAQAA3gIAMNQBAACOAwAw1QEAAOECADAJBgAAtQIAIAkAALYCACCWAQEAAAABmgFAAAAAAZsBQAAAAAG0AQIAAAABtQEBAAAAAbYBAQAAAAG3AQEAAAABAgAAABgAIBcAAJEDACADAAAAGAAgFwAAkQMAIBgAAJADACABEAAAyQMAMAIAAAAYACAQAACQAwAgAgAAAOICACAQAACPAwAgB5YBAQCdAgAhmgFAAJ4CACGbAUAAngIAIbQBAgCxAgAhtQEBAKMCACG2AQEAnQIAIbcBAQCdAgAhCQYAALICACAJAACzAgAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhtAECALECACG1AQEAowIAIbYBAQCdAgAhtwEBAJ0CACEJBgAAtQIAIAkAALYCACCWAQEAAAABmgFAAAAAAZsBQAAAAAG0AQIAAAABtQEBAAAAAbYBAQAAAAG3AQEAAAABCAYAAMUCACAKAADEAgAglgEBAAAAAZoBQAAAAAGbAUAAAAABtgEBAAAAAbgBQAAAAAG6AQAAALoBAgIAAAATACAXAACaAwAgAwAAABMAIBcAAJoDACAYAACZAwAgARAAAMgDADACAAAAEwAgEAAAmQMAIAIAAADuAgAgEAAAmAMAIAaWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG2AQEAnQIAIbgBQACeAgAhugEAALsCugEiCAYAAL0CACAKAAC8AgAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhtgEBAJ0CACG4AUAAngIAIboBAAC7AroBIggGAADFAgAgCgAAxAIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAbYBAQAAAAG4AUAAAAABugEAAAC6AQILCAAA_gIAIAkAAPQCACAKAAD1AgAglgEBAAAAAZoBQAAAAAGbAUAAAAABvwEBAAAAAcABAgAAAAHBAQIAAAABwgEgAAAAAcMBAQAAAAECAAAADgAgFwAAmwMAIAMAAAALACAXAACbAwAgGAAAnwMAIA0AAAALACAIAAD9AgAgCQAA2AIAIAoAANkCACAQAACfAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhvwEBAKMCACHAAQIAsQIAIcEBAgCxAgAhwgEgANUCACHDAQEAnQIAIQsIAAD9AgAgCQAA2AIAIAoAANkCACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG_AQEAowIAIcABAgCxAgAhwQECALECACHCASAA1QIAIcMBAQCdAgAhDJYBAQAAAAGaAUAAAAABmwFAAAAAAacBAQAAAAGoAQEAAAABqgEBAAAAAasBAQAAAAGsAQEAAAABrQFAAAAAAa4BQAAAAAGvAQEAAAABsAEBAAAAAQIAAAAJACAXAACrAwAgAwAAAAkAIBcAAKsDACAYAACqAwAgARAAAMcDADARAwAAkQIAIJMBAACXAgAwlAEAAAcAEJUBAACXAgAwlgEBAAAAAZoBQADjAQAhmwFAAOMBACGnAQEA4gEAIagBAQDiAQAhqQEBAOIBACGqAQEAhgIAIasBAQCGAgAhrAEBAIYCACGtAUAAmAIAIa4BQACYAgAhrwEBAIYCACGwAQEAhgIAIQIAAAAJACAQAACqAwAgAgAAAKgDACAQAACpAwAgEJMBAACnAwAwlAEAAKgDABCVAQAApwMAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIacBAQDiAQAhqAEBAOIBACGpAQEA4gEAIaoBAQCGAgAhqwEBAIYCACGsAQEAhgIAIa0BQACYAgAhrgFAAJgCACGvAQEAhgIAIbABAQCGAgAhEJMBAACnAwAwlAEAAKgDABCVAQAApwMAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIacBAQDiAQAhqAEBAOIBACGpAQEA4gEAIaoBAQCGAgAhqwEBAIYCACGsAQEAhgIAIa0BQACYAgAhrgFAAJgCACGvAQEAhgIAIbABAQCGAgAhDJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIacBAQCdAgAhqAEBAJ0CACGqAQEAowIAIasBAQCjAgAhrAEBAKMCACGtAUAApAIAIa4BQACkAgAhrwEBAKMCACGwAQEAowIAIQyWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGnAQEAnQIAIagBAQCdAgAhqgEBAKMCACGrAQEAowIAIawBAQCjAgAhrQFAAKQCACGuAUAApAIAIa8BAQCjAgAhsAEBAKMCACEMlgEBAAAAAZoBQAAAAAGbAUAAAAABpwEBAAAAAagBAQAAAAGqAQEAAAABqwEBAAAAAawBAQAAAAGtAUAAAAABrgFAAAAAAa8BAQAAAAGwAQEAAAABB5YBAQAAAAGZAUAAAAABmgFAAAAAAZsBQAAAAAGxAQEAAAABsgEBAAAAAbMBAQAAAAECAAAABQAgFwAAtwMAIAMAAAAFACAXAAC3AwAgGAAAtgMAIAEQAADGAwAwDAMAAJECACCTAQAAmQIAMJQBAAADABCVAQAAmQIAMJYBAQAAAAGZAUAA4wEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbEBAQAAAAGyAQEAhgIAIbMBAQCGAgAhAgAAAAUAIBAAALYDACACAAAAtAMAIBAAALUDACALkwEAALMDADCUAQAAtAMAEJUBAACzAwAwlgEBAOIBACGZAUAA4wEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbEBAQDiAQAhsgEBAIYCACGzAQEAhgIAIQuTAQAAswMAMJQBAAC0AwAQlQEAALMDADCWAQEA4gEAIZkBQADjAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhsQEBAOIBACGyAQEAhgIAIbMBAQCGAgAhB5YBAQCdAgAhmQFAAJ4CACGaAUAAngIAIZsBQACeAgAhsQEBAJ0CACGyAQEAowIAIbMBAQCjAgAhB5YBAQCdAgAhmQFAAJ4CACGaAUAAngIAIZsBQACeAgAhsQEBAJ0CACGyAQEAowIAIbMBAQCjAgAhB5YBAQAAAAGZAUAAAAABmgFAAAAAAZsBQAAAAAGxAQEAAAABsgEBAAAAAbMBAQAAAAEEFwAArAMAMM0BAACtAwAw0QEAALADADDSAQAArwMAIAQXAACgAwAwzQEAAKEDADDRAQAApAMAMNIBAACjAwAgAxcAAJsDACDNAQAAnAMAINEBAAAOACAEFwAAkgMAMM0BAACTAwAw0QEAAOoCADDSAQAAlQMAIAQXAACJAwAwzQEAAIoDADDRAQAA3gIAMNIBAACMAwAgAAAFAwAAwwMAIAgAAMUDACAJAADAAwAgCgAAwQMAIL8BAACfAgAgAAADAwAAwwMAIAYAAL8DACAKAADEAwAgBwQAAL0DACAFAAC-AwAgBgAAvwMAIAkAAMADACAKAADBAwAgyAEAAJ8CACDJAQAAnwIAIAQDAADDAwAgBgAAvwMAIAkAAMIDACC1AQAAnwIAIAEGAAD3AgAgB5YBAQAAAAGZAUAAAAABmgFAAAAAAZsBQAAAAAGxAQEAAAABsgEBAAAAAbMBAQAAAAEMlgEBAAAAAZoBQAAAAAGbAUAAAAABpwEBAAAAAagBAQAAAAGqAQEAAAABqwEBAAAAAawBAQAAAAGtAUAAAAABrgFAAAAAAa8BAQAAAAGwAQEAAAABBpYBAQAAAAGaAUAAAAABmwFAAAAAAbYBAQAAAAG4AUAAAAABugEAAAC6AQIHlgEBAAAAAZoBQAAAAAGbAUAAAAABtAECAAAAAbUBAQAAAAG2AQEAAAABtwEBAAAAAQKWAQEAAAABuwEBAAAAAQIAAABPACAXAADKAwAgAwAAAFIAIBcAAMoDACAYAADOAwAgBAAAAFIAIBAAAM4DACCWAQEAnQIAIbsBAQCdAgAhApYBAQCdAgAhuwEBAJ0CACEOBAAAuAMAIAUAALkDACAJAAC7AwAgCgAAvAMAIJYBAQAAAAGaAUAAAAABmwFAAAAAAboBAAAAywECuwEBAAAAAcQBAQAAAAHFASAAAAABxwEAAADHAQLIAQEAAAAByQEBAAAAAQIAAAABACAXAADPAwAgBpYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG4AUAAAAABugEAAAC6AQIHlgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbQBAgAAAAG1AQEAAAABtwEBAAAAAQMAAAAjACAXAADPAwAgGAAA1QMAIBAAAAAjACAEAACEAwAgBQAAhQMAIAkAAIcDACAKAACIAwAgEAAA1QMAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIboBAACDA8sBIrsBAQCdAgAhxAEBAJ0CACHFASAA1QIAIccBAACCA8cBIsgBAQCjAgAhyQEBAKMCACEOBAAAhAMAIAUAAIUDACAJAACHAwAgCgAAiAMAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIboBAACDA8sBIrsBAQCdAgAhxAEBAJ0CACHFASAA1QIAIccBAACCA8cBIsgBAQCjAgAhyQEBAKMCACEIlgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAb8BAQAAAAHAAQIAAAABwQECAAAAAcIBIAAAAAEOBAAAuAMAIAUAALkDACAGAAC6AwAgCgAAvAMAIJYBAQAAAAGaAUAAAAABmwFAAAAAAboBAAAAywECuwEBAAAAAcQBAQAAAAHFASAAAAABxwEAAADHAQLIAQEAAAAByQEBAAAAAQIAAAABACAXAADXAwAgDAMAAPMCACAIAAD-AgAgCgAA9QIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG_AQEAAAABwAECAAAAAcEBAgAAAAHCASAAAAABwwEBAAAAAQIAAAAOACAXAADZAwAgAwAAACMAIBcAANcDACAYAADdAwAgEAAAACMAIAQAAIQDACAFAACFAwAgBgAAhgMAIAoAAIgDACAQAADdAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQ4EAACEAwAgBQAAhQMAIAYAAIYDACAKAACIAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQMAAAALACAXAADZAwAgGAAA4AMAIA4AAAALACADAADXAgAgCAAA_QIAIAoAANkCACAQAADgAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhqQEBAJ0CACG_AQEAowIAIcABAgCxAgAhwQECALECACHCASAA1QIAIcMBAQCdAgAhDAMAANcCACAIAAD9AgAgCgAA2QIAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhvwEBAKMCACHAAQIAsQIAIcEBAgCxAgAhwgEgANUCACHDAQEAnQIAIQ4EAAC4AwAgBQAAuQMAIAYAALoDACAJAAC7AwAglgEBAAAAAZoBQAAAAAGbAUAAAAABugEAAADLAQK7AQEAAAABxAEBAAAAAcUBIAAAAAHHAQAAAMcBAsgBAQAAAAHJAQEAAAABAgAAAAEAIBcAAOEDACAJAwAAxgIAIAYAAMUCACCWAQEAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABtgEBAAAAAbgBQAAAAAG6AQAAALoBAgIAAAATACAXAADjAwAgDAMAAPMCACAIAAD-AgAgCQAA9AIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG_AQEAAAABwAECAAAAAcEBAgAAAAHCASAAAAABwwEBAAAAAQIAAAAOACAXAADlAwAgAwAAACMAIBcAAOEDACAYAADpAwAgEAAAACMAIAQAAIQDACAFAACFAwAgBgAAhgMAIAkAAIcDACAQAADpAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQ4EAACEAwAgBQAAhQMAIAYAAIYDACAJAACHAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQMAAAARACAXAADjAwAgGAAA7AMAIAsAAAARACADAAC-AgAgBgAAvQIAIBAAAOwDACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbYBAQCdAgAhuAFAAJ4CACG6AQAAuwK6ASIJAwAAvgIAIAYAAL0CACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbYBAQCdAgAhuAFAAJ4CACG6AQAAuwK6ASIDAAAACwAgFwAA5QMAIBgAAO8DACAOAAAACwAgAwAA1wIAIAgAAP0CACAJAADYAgAgEAAA7wMAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhvwEBAKMCACHAAQIAsQIAIcEBAgCxAgAhwgEgANUCACHDAQEAnQIAIQwDAADXAgAgCAAA_QIAIAkAANgCACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIb8BAQCjAgAhwAECALECACHBAQIAsQIAIcIBIADVAgAhwwEBAJ0CACEOBQAAuQMAIAYAALoDACAJAAC7AwAgCgAAvAMAIJYBAQAAAAGaAUAAAAABmwFAAAAAAboBAAAAywECuwEBAAAAAcQBAQAAAAHFASAAAAABxwEAAADHAQLIAQEAAAAByQEBAAAAAQIAAAABACAXAADwAwAgAwAAACMAIBcAAPADACAYAAD0AwAgEAAAACMAIAUAAIUDACAGAACGAwAgCQAAhwMAIAoAAIgDACAQAAD0AwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQ4FAACFAwAgBgAAhgMAIAkAAIcDACAKAACIAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQ4EAAC4AwAgBgAAugMAIAkAALsDACAKAAC8AwAglgEBAAAAAZoBQAAAAAGbAUAAAAABugEAAADLAQK7AQEAAAABxAEBAAAAAcUBIAAAAAHHAQAAAMcBAsgBAQAAAAHJAQEAAAABAgAAAAEAIBcAAPUDACADAAAAIwAgFwAA9QMAIBgAAPkDACAQAAAAIwAgBAAAhAMAIAYAAIYDACAJAACHAwAgCgAAiAMAIBAAAPkDACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG6AQAAgwPLASK7AQEAnQIAIcQBAQCdAgAhxQEgANUCACHHAQAAggPHASLIAQEAowIAIckBAQCjAgAhDgQAAIQDACAGAACGAwAgCQAAhwMAIAoAAIgDACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG6AQAAgwPLASK7AQEAnQIAIcQBAQCdAgAhxQEgANUCACHHAQAAggPHASLIAQEAowIAIckBAQCjAgAhBgQGAgUKAwYMBAcACgkcBwodCAEDAAEBAwABBQMAAQcACQgABQkUBwoZCAIGDwQHAAYBBhAAAwMAAQYABAoWCAMDAAEGAAQJAAcCCRoAChsABAQeAAUfAAkgAAohAAAAAAMHAA8dABAeABEAAAADBwAPHQAQHgARAgMAAQgABQIDAAEIAAUFBwAWHQAZHgAaLwAXMAAYAAAAAAAFBwAWHQAZHgAaLwAXMAAYAAADBwAfHQAgHgAhAAAAAwcAHx0AIB4AIQIDAAEGAAQCAwABBgAEAwcAJh0AJx4AKAAAAAMHACYdACceACgDAwABBgAECQAHAwMAAQYABAkABwUHAC0dADAeADEvAC4wAC8AAAAAAAUHAC0dADAeADEvAC4wAC8BAwABAQMAAQMHADYdADceADgAAAADBwA2HQA3HgA4AQMAAQEDAAEDBwA9HQA-HgA_AAAAAwcAPR0APh4APwAAAAMHAEUdAEYeAEcAAAADBwBFHQBGHgBHCwIBDCIBDSUBDiYBDycBESkBEisLEywMFC4BFTALFjENGTIBGjMBGzQLHzcOIDgSITkEIjoEIzsEJDwEJT0EJj8EJ0ELKEITKUQEKkYLK0cULEgELUkELkoLMU0VMk4bM1AFNFEFNVQFNlUFN1YFOFgFOVoLOlscO10FPF8LPWAdPmEFP2IFQGMLQWYeQmciQ2gHRGkHRWoHRmsHR2wHSG4HSXALSnEjS3MHTHULTXYkTncHT3gHUHkLUXwlUn0pU34IVH8IVYABCFaBAQhXggEIWIQBCFmGAQtahwEqW4kBCFyLAQtdjAErXo0BCF-OAQhgjwELYZIBLGKTATJjlAECZJUBAmWWAQJmlwECZ5gBAmiaAQJpnAELap0BM2ufAQJsoQELbaIBNG6jAQJvpAECcKUBC3GoATVyqQE5c6oBA3SrAQN1rAEDdq0BA3euAQN4sAEDebIBC3qzATp7tQEDfLcBC324ATt-uQEDf7oBA4ABuwELgQG-ATyCAb8BQIMBwQFBhAHCAUGFAcUBQYYBxgFBhwHHAUGIAckBQYkBywELigHMAUKLAc4BQYwB0AELjQHRAUOOAdIBQY8B0wFBkAHUAQuRAdcBRJIB2AFI"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/lib/auth.ts
var auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "sqlite"
    // or "mysql", "postgresql", ...etc
  }),
  trustedOrigins: [process.env.APP_URL],
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: false,
    autoLoginAfterRegister: false
  },
  user: {
    additionalFields: {
      role: {
        type: "string",
        defaultValue: "STUDENT",
        required: false
      },
      status: {
        type: "string",
        defaultValue: "ACTIVE",
        required: false
      },
      phone: {
        type: "string",
        required: false
      }
    }
  }
});

// src/app.ts
import cors from "cors";

// src/modules/booking/booking.router.ts
import { Router } from "express";

// src/modules/booking/booking.service.ts
var createBooking = async (payload, userId) => {
  const existTutorProfile = await prisma.tutorProfile.findUnique({
    where: {
      id: payload.tutorId
    }
  });
  const activeBookingCount = await prisma.booking.count({
    where: {
      userId,
      tutorId: payload.tutorId,
      status: {
        in: ["PENDING", "CONFIRMED"]
      }
    }
  });
  if (activeBookingCount > 0) {
    throw new Error("You already have an active booking");
  }
  if (!existTutorProfile) {
    throw new Error("Tutor profile not exist!!");
  }
  if (existTutorProfile && !existTutorProfile.availablity) {
    throw new Error("Tutor not available right now");
  }
  const result = await prisma.booking.create({
    data: {
      ...payload,
      userId
    }
  });
  return result;
};
var getBooking = async (payload, userId, role) => {
  let booking = [];
  let totalBooking = 0;
  if (role === "STUDENT") {
    booking = await prisma.booking.findMany({
      where: {
        userId
      },
      include: {
        tutor: true
      },
      skip: payload.skip,
      take: payload.limit
    });
    totalBooking = await prisma.booking.count({
      where: {
        userId
      }
    });
  }
  if (role === "TUTOR") {
    const tutorProfile = await prisma.tutorProfile.findUnique({
      where: {
        userId
      }
    });
    if (!tutorProfile) {
      throw new Error("Tutor profile not found so no booking here");
    }
    booking = await prisma.booking.findMany({
      where: {
        tutorId: tutorProfile.id,
        status: {
          in: ["PENDING", "CONFIRMED", "COMPLETED"]
        }
      },
      include: {
        user: true
      },
      skip: payload.skip,
      take: payload.limit
    });
    totalBooking = await prisma.booking.count({
      where: {
        tutorId: tutorProfile.id
      }
    });
  }
  if (role === "ADMIN") {
    booking = await prisma.booking.findMany({
      include: {
        tutor: true,
        user: true
      },
      skip: payload.skip,
      take: payload.limit
    });
    totalBooking = await prisma.booking.count();
  }
  const formattedBookings = booking.map((b) => {
    return {
      id: b.id,
      status: b.status,
      user: b.user,
      tutor: b.tutor,
      createdAt: b.createdAt,
      updatedAt: b.updatedAt
    };
  });
  return {
    data: formattedBookings,
    paginations: {
      totalBooking,
      page: payload.page,
      limit: payload.limit,
      totalPage: Math.ceil(totalBooking / payload.limit)
    }
  };
};
var getBookingById = async (userId, bookingId, role) => {
  const existBooking = await prisma.booking.findUnique({
    where: {
      id: bookingId
    }
  });
  if (!existBooking) {
    throw new Error("Booking not found");
  }
  if (role === "STUDENT") {
    return await prisma.booking.findFirst({
      where: {
        id: existBooking.id,
        userId
      },
      include: {
        tutor: true
      }
    });
  }
  if (role === "TUTOR") {
    const tutorProfile = await prisma.tutorProfile.findUnique({
      where: {
        userId
      }
    });
    if (!tutorProfile) {
      throw new Error("Tutor profile not found");
    }
    return await prisma.booking.findFirst({
      where: {
        id: existBooking.id,
        tutorId: tutorProfile.id
      },
      include: {
        user: true
      }
    });
  }
  if (role === "ADMIN") {
    return await prisma.booking.findUnique({
      where: {
        id: existBooking.id
      },
      include: {
        tutor: true,
        user: true
      }
    });
  }
  throw new Error("Invalid role provided");
};
var cancelBooking = async (payload, userId, bookingId) => {
  const bookingData = await prisma.booking.findFirst({
    where: {
      id: bookingId,
      userId
    }
  });
  if (!bookingData) {
    throw new Error("Booking not found");
  }
  if (bookingData.status !== "PENDING") {
    throw new Error("You can only cancel pending booking");
  }
  return await prisma.booking.update({
    where: {
      id: bookingData.id
    },
    data: {
      ...payload
    }
  });
};
var updateBooking = async (payload, tutorId, bookingId) => {
  const existTutorProfile = await prisma.tutorProfile.findFirst({
    where: {
      userId: tutorId
    }
  });
  if (!existTutorProfile) {
    throw new Error("Tutor profile not found");
  }
  const bookingData = await prisma.booking.findUnique({
    where: {
      id: bookingId
    }
  });
  if (!bookingData) {
    throw new Error("Booking not found");
  }
  if (bookingData.tutorId !== existTutorProfile.id) {
    throw new Error("You cann't access this part");
  }
  return await prisma.booking.update({
    where: {
      id: bookingData.id
    },
    data: {
      ...payload
    }
  });
};
var bookingService = {
  createBooking,
  getBooking,
  getBookingById,
  updateBooking,
  cancelBooking
};

// src/helpers/paginationSortHelpers.ts
var paginationSortHelpers = (options) => {
  const page = Number(options.page || 1);
  const limit = Number(options.limit || 10);
  const skip = (page - 1) * limit;
  const sortBy = options.sortBy || "createdAt";
  const sortOrder = options.sortOrder || "desc";
  return {
    page,
    limit,
    skip,
    sortBy,
    sortOrder
  };
};
var paginationSortHelpers_default = paginationSortHelpers;

// src/modules/booking/booking.controller.ts
var createBooking2 = async (req, res) => {
  try {
    const user = req.user;
    if (!user) {
      res.status(403).json({
        message: "You are Unauthorized!!!"
      });
    }
    const result = await bookingService.createBooking(
      req.body,
      user?.id
    );
    res.status(201).json({
      message: "Booking Created Successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var getBooking2 = async (req, res) => {
  try {
    const user = req.user;
    console.log(user);
    const { page, limit, skip, sortBy, sortOrder } = paginationSortHelpers_default(
      req.query
    );
    const result = await bookingService.getBooking(
      { page, limit, skip, sortBy, sortOrder },
      user?.id,
      user?.role
    );
    res.status(201).json({
      message: "Booking fetched successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var getBookingById2 = async (req, res) => {
  try {
    const user = req.user;
    const bookingId = req.params.bookingId;
    const result = await bookingService.getBookingById(
      user?.id,
      bookingId,
      user?.role
    );
    res.status(201).json({
      message: "Booking Fetched successfully by id",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var cancelBooking2 = async (req, res) => {
  try {
    const user = req.user;
    const bookingId = req.params.bookingId;
    const result = await bookingService.cancelBooking(
      req.body,
      user?.id,
      bookingId
    );
    res.status(201).json({
      message: "Booking cancelled successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var updateBooking2 = async (req, res) => {
  try {
    const user = req.user;
    const bookingId = req.params.bookingId;
    const result = await bookingService.updateBooking(
      req.body,
      user?.id,
      bookingId
    );
    res.status(201).json({
      message: "Booking upadated successfully by tutor",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var bookingController = {
  createBooking: createBooking2,
  getBooking: getBooking2,
  getBookingById: getBookingById2,
  updateBooking: updateBooking2,
  cancelBooking: cancelBooking2
};

// src/middlewares/auth.ts
var auth2 = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      console.log(session?.user);
      if (!session) {
        return res.status(401).json({
          success: false,
          message: "You are unauthorized!!!"
        });
      }
      if (!session?.user.emailVerified) {
        return res.status(403).json({
          success: false,
          message: "Plz verify your email"
        });
      }
      req.user = {
        id: session?.user.id,
        name: session?.user.name,
        email: session?.user.email,
        role: session?.user.role,
        emailVerify: session?.user.emailVerified
      };
      if (roles.length && !roles.includes(req.user.role)) {
        return res.status(403).json({
          success: false,
          message: "you don't have permission to acces this part"
        });
      }
      next();
    } catch (error) {
      next(error);
    }
  };
};
var auth_default = auth2;

// src/modules/booking/booking.router.ts
var router = Router();
router.post("/", auth_default("STUDENT" /* STUDENT */), bookingController.createBooking);
router.get(
  "/",
  auth_default("STUDENT" /* STUDENT */, "TUTOR" /* TUTOR */, "ADMIN" /* ADMIN */),
  bookingController.getBooking
);
router.get(
  "/:bookingId",
  auth_default("STUDENT" /* STUDENT */, "TUTOR" /* TUTOR */, "ADMIN" /* ADMIN */),
  bookingController.getBookingById
);
router.patch(
  "/:bookingId/cancel",
  auth_default("STUDENT" /* STUDENT */),
  bookingController.cancelBooking
);
router.patch(
  "/:bookingId/status",
  auth_default("TUTOR" /* TUTOR */),
  bookingController.updateBooking
);
var bookingRouter = router;

// src/modules/category/category.router.ts
import { Router as Router2 } from "express";

// src/modules/category/category.service.ts
var createCategory = async (payload) => {
  console.log("payload", payload);
  const result = await prisma.category.create({
    data: {
      ...payload
    }
  });
  return result;
};
var getCategory = async () => {
  const result = await prisma.category.findMany();
  return result;
};
var getCategoryById = async (categoryId) => {
  const existCategory = await prisma.category.findUnique({
    where: {
      id: categoryId
    }
  });
  if (!existCategory) {
    throw new Error("Category not found");
  }
  return await prisma.category.findFirst({
    where: {
      id: existCategory.id
    }
  });
};
var updateCategory = async (payload, categoryId) => {
  const existCategory = await prisma.category.findUnique({
    where: {
      id: categoryId
    }
  });
  const existTutor = await prisma.tutorProfile.findFirst({
    where: {
      categoryId
    }
  });
  if (!existCategory) {
    throw new Error("Category not found");
  }
  if (existTutor) {
    throw new Error("You Cannot update category with assigned tutors");
  }
  return await prisma.category.update({
    where: {
      id: categoryId
    },
    data: {
      ...payload
    }
  });
};
var deleteCategory = async (categoryId) => {
  const existCategory = await prisma.category.findUnique({
    where: {
      id: categoryId
    }
  });
  const existTutor = await prisma.tutorProfile.findFirst({
    where: {
      categoryId
    }
  });
  if (!existCategory) {
    throw new Error("Category not found");
  }
  if (existTutor) {
    throw new Error("You Cannot delete category with assigned tutors");
  }
  return await prisma.category.delete({
    where: {
      id: categoryId
    }
  });
};
var categoryService = {
  createCategory,
  getCategory,
  getCategoryById,
  updateCategory,
  deleteCategory
};

// src/modules/category/category.controller.ts
var createCategory2 = async (req, res) => {
  console.log("body", req.body);
  const result = await categoryService.createCategory(req.body);
  res.status(201).json({
    message: "Category Created successfully",
    data: result
  });
};
var getCategory2 = async (req, res) => {
  const result = await categoryService.getCategory();
  res.status(201).json({
    message: "Category fetched successfully",
    data: result
  });
  return result;
};
var getCategoryById2 = async (req, res) => {
  try {
    const categoryId = req.params.categoryId;
    const result = await categoryService.getCategoryById(categoryId);
    res.status(201).json({
      message: "Category fetched successfully by Id",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var updateCategory2 = async (req, res) => {
  try {
    const categoryId = req.params.categoryId;
    const result = await categoryService.updateCategory(
      req.body,
      categoryId
    );
    res.status(201).json({
      message: "Category updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var deleteCategory2 = async (req, res) => {
  try {
    const categoryId = req.params.categoryId;
    const result = await categoryService.deleteCategory(categoryId);
    res.status(201).json({
      message: "Category deleted successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var categoryController = {
  createCategory: createCategory2,
  getCategory: getCategory2,
  getCategoryById: getCategoryById2,
  updateCategory: updateCategory2,
  deleteCategory: deleteCategory2
};

// src/modules/category/category.router.ts
var router2 = Router2();
router2.post("/", auth_default("ADMIN" /* ADMIN */), categoryController.createCategory);
router2.get("/", categoryController.getCategory);
router2.get("/:categoryId", categoryController.getCategoryById);
router2.patch(
  "/:categoryId",
  auth_default("ADMIN" /* ADMIN */),
  categoryController.updateCategory
);
router2.delete(
  "/:categoryId",
  auth_default("ADMIN" /* ADMIN */),
  categoryController.deleteCategory
);
var categoryRouter = router2;

// src/modules/tutor/tutor.router.ts
import { Router as Router3 } from "express";

// src/modules/tutor/tutor.service.ts
var createTutor = async (payload, userId) => {
  const existingTutor = await prisma.tutorProfile.findUnique({
    where: {
      userId
    }
  });
  if (existingTutor) {
    throw new Error("Tutor profile already exits!!!");
  }
  const result = await prisma.tutorProfile.create({
    data: {
      ...payload,
      userId
    }
  });
  return result;
};
var getTutor = async (payload) => {
  const allAndConditions = [];
  if (payload.search) {
    allAndConditions.push({
      category: {
        is: {
          name: {
            contains: payload.search,
            mode: "insensitive"
          }
        }
      }
    });
  }
  const tutors = await prisma.tutorProfile.findMany({
    take: payload.limit,
    skip: payload.skip,
    where: {
      AND: allAndConditions
    },
    orderBy: payload.sortBy && payload.sortOrder ? {
      [payload.sortBy]: payload.sortOrder
    } : { createdAt: "desc" },
    include: {
      category: true,
      user: true,
      _count: {
        select: {
          booking: true,
          review: true
        }
      },
      review: {
        select: {
          rating: true
        }
      }
    }
  });
  const formattedTutors = tutors.map((tutor) => {
    const totalReview = tutor.review.length;
    const averageRating = totalReview > 0 ? Number(
      tutor.review.reduce((acc, r) => acc + r.rating, 0) / totalReview
    ) : 0;
    return {
      id: tutor.id,
      bio: tutor.bio,
      category: tutor.category,
      user: tutor.user,
      totalBookings: tutor._count.booking,
      totalReview,
      averageRating
    };
  });
  const total = await prisma.tutorProfile.count({
    where: {
      AND: allAndConditions
    }
  });
  return {
    data: formattedTutors,
    paginations: {
      total,
      page: payload.page,
      limit: payload.limit,
      totalPage: Math.ceil(total / payload.limit)
    }
  };
};
var getTutorById = async (tutorId) => {
  const tutor = await prisma.tutorProfile.findUnique({
    where: {
      id: tutorId
    },
    include: {
      category: true,
      user: true,
      _count: {
        select: {
          booking: true,
          review: true
        }
      },
      review: {
        select: {
          rating: true
        }
      }
    }
  });
  if (!tutor) {
    throw new Error("Tutor not found");
  }
  const totalReview = tutor.review.length;
  const averageRating = totalReview > 0 ? Number(tutor.review.reduce((acc, r) => acc + r.rating, 0) / totalReview) : 0;
  const formattedTutor = {
    id: tutor.id,
    bio: tutor.bio,
    category: tutor.category,
    user: tutor.user,
    totalBookings: tutor._count.booking,
    totalReview,
    averageRating
  };
  return formattedTutor;
};
var updateTutor = async (payload, userId, tutorId) => {
  const tutorProfileData = await prisma.tutorProfile.findUnique({
    where: {
      id: tutorId
    }
  });
  console.log(tutorProfileData);
  if (!tutorProfileData) {
    throw new Error("Tutor not found");
  }
  if (tutorProfileData.userId !== userId) {
    throw new Error("You are not allowed to access this part");
  }
  return await prisma.tutorProfile.update({
    where: {
      id: tutorProfileData.id
    },
    data: {
      ...payload
    }
  });
};
var deleteTutor = async (tutorId) => {
  const existBooking = await prisma.booking.findFirst({
    where: {
      tutorId
    }
  });
  if (existBooking) {
    throw new Error("You cann't delete tutor with existing bookings");
  }
  return await prisma.tutorProfile.delete({
    where: {
      id: tutorId
    }
  });
};
var tutorService = {
  createTutor,
  getTutor,
  getTutorById,
  updateTutor,
  deleteTutor
};

// src/modules/tutor/tutor.controller.ts
var createTutor2 = async (req, res) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(403).json({
        message: "You ar unauthorized!!"
      });
    }
    const result = await tutorService.createTutor(req.body, user?.id);
    res.status(201).json({
      message: "Tutor Profile Created Successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var getTutor2 = async (req, res) => {
  try {
    const search = typeof req.query.search === "string" ? req.query.search : void 0;
    const { page, limit, skip, sortBy, sortOrder } = paginationSortHelpers_default(
      req.query
    );
    const result = await tutorService.getTutor({
      search,
      page,
      limit,
      skip,
      sortBy,
      sortOrder
    });
    res.status(201).json({
      message: "Tutor fetched successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var getTutorById2 = async (req, res) => {
  try {
    const tutorId = req.params.tutorId;
    const result = await tutorService.getTutorById(tutorId);
    res.status(201).json({
      message: "Tutor Fetched successfully by Id",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var updateTutor2 = async (req, res) => {
  try {
    const tutorId = req.params.tutorId;
    const user = req.user;
    if (!user) {
      res.status(403).json({
        message: "You are unauthorized"
      });
    }
    const result = await tutorService.updateTutor(
      req.body,
      user?.id,
      tutorId
    );
    res.status(201).json({
      message: "Tutor updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var deleteTutor2 = async (req, res) => {
  try {
    const tutorId = req.params.tutorId;
    const result = await tutorService.deleteTutor(tutorId);
    res.status(201).json({
      message: "Tutor updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var tutorController = {
  createTutor: createTutor2,
  getTutor: getTutor2,
  getTutorById: getTutorById2,
  updateTutor: updateTutor2,
  deleteTutor: deleteTutor2
};

// src/modules/tutor/tutor.router.ts
var router3 = Router3();
router3.post("/", auth_default("TUTOR" /* TUTOR */), tutorController.createTutor);
router3.get("/", tutorController.getTutor);
router3.get("/:tutorId", tutorController.getTutorById);
router3.put("/:tutorId", auth_default("TUTOR" /* TUTOR */), tutorController.updateTutor);
router3.delete("/:tutorId", auth_default("ADMIN" /* ADMIN */), tutorController.deleteTutor);
var tutorRouter = router3;

// src/modules/review/review.router.ts
import { Router as Router4 } from "express";

// src/modules/review/review.service.ts
var createReview = async (payload, userId) => {
  const existBooking = await prisma.booking.findFirst({
    where: {
      id: payload.bookingId
    }
  });
  const alreadyReviewed = await prisma.review.findUnique({
    where: {
      bookingId: payload.bookingId
    }
  });
  if (alreadyReviewed) {
    throw new Error(
      "You cann't reviewed again because you already reviewed this session"
    );
  }
  if (!existBooking) {
    throw new Error("Booking not found");
  }
  if (existBooking.status !== "COMPLETED") {
    throw new Error(
      "You cann't review this tutor because session is not completed"
    );
  }
  if (existBooking.userId !== userId || existBooking.tutorId !== payload.tutorId) {
    throw new Error("You cann't review this tutor because he is not your user");
  }
  const result = await prisma.review.create({
    data: {
      ...payload,
      userId
    }
  });
  return result;
};
var getReview = async () => {
  const result = await prisma.review.findMany();
  return result;
};
var getReviewById = async (reviewId) => {
  const result = await prisma.review.findUnique({
    where: {
      id: reviewId
    }
  });
  return result;
};
var updateReview = async (payload, userId, reviewId) => {
  const existReview = await prisma.review.findUnique({
    where: {
      id: reviewId
    }
  });
  if (!existReview) {
    throw new Error("You don't reviewed any tutor!!");
  }
  if (existReview.userId !== userId) {
    throw new Error("You are not allowed to update this review");
  }
  const updateReview3 = await prisma.review.update({
    where: {
      id: reviewId
    },
    data: {
      ...payload
    }
  });
  return updateReview3;
};
var deleteReview = async (payload, userId, reviewId, role) => {
  const existReview = await prisma.review.findUnique({
    where: {
      id: reviewId
    }
  });
  if (!existReview) {
    throw new Error("Review not found!!");
  }
  if (role === "STUDENT" && existReview.userId !== userId) {
    throw new Error("You can delete only your own review");
  }
  return await prisma.review.delete({
    where: {
      id: reviewId
    }
  });
};
var reviewService = {
  createReview,
  getReview,
  updateReview,
  getReviewById,
  deleteReview
};

// src/modules/review/review.controller.ts
var createReview2 = async (req, res) => {
  try {
    const user = req.user;
    if (!user) {
      res.status(403).json({
        message: "You ar unauthorized!!"
      });
    }
    const result = await reviewService.createReview(
      req.body,
      user?.id
    );
    res.status(201).json({
      message: "Review Created successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var getReview2 = async (req, res) => {
  const result = await reviewService.getReview();
  res.status(201).json({
    message: "Review fetched successfully",
    data: result
  });
};
var getReviewById2 = async (req, res) => {
  try {
    const reviewId = req.params.reviewId;
    const result = await reviewService.getReviewById(reviewId);
    res.status(201).json({
      message: "Review fetched successfully by id",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var updateReview2 = async (req, res) => {
  try {
    const user = req.user;
    const reviewId = req.params.reviewId;
    const result = await reviewService.updateReview(
      req.body,
      user?.id,
      reviewId
    );
    res.status(201).json({
      message: "Review updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var deleteReview2 = async (req, res) => {
  try {
    const user = req.user;
    const reviewId = req.params.reviewId;
    const result = await reviewService.deleteReview(req.body, user?.id, reviewId, user?.role);
    res.status(201).json({
      message: "Review updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var reviewController = {
  createReview: createReview2,
  getReview: getReview2,
  updateReview: updateReview2,
  getReviewById: getReviewById2,
  deleteReview: deleteReview2
};

// src/modules/review/review.router.ts
var router4 = Router4();
router4.post("/", auth_default("STUDENT" /* STUDENT */), reviewController.createReview);
router4.get("/", reviewController.getReview);
router4.get("/:reviewId", reviewController.getReviewById);
router4.patch(
  "/:reviewId",
  auth_default("STUDENT" /* STUDENT */),
  reviewController.updateReview
);
router4.delete("/:reviewId", auth_default("STUDENT" /* STUDENT */, "ADMIN" /* ADMIN */), reviewController.deleteReview);
var reviewRouter = router4;

// src/app.ts
var app = express();
var allowedOrigins = [
  process.env.APP_URL || "http://localhost:3000"
].filter(Boolean);
app.use(
  cors({
    origin: (origin, callback) => {
      if (!origin) return callback(null, true);
      const isAllowed = allowedOrigins.includes(origin) || /^https:\/\/next-blog-client.*\.vercel\.app$/.test(origin) || /^https:\/\/.*\.vercel\.app$/.test(origin);
      if (isAllowed) {
        callback(null, true);
      } else {
        callback(new Error(`Origin ${origin} not allowed by CORS`));
      }
    },
    credentials: true,
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization", "Cookie"],
    exposedHeaders: ["Set-Cookie"]
  })
);
app.use(express.json());
app.all("/api/auth/*splat", toNodeHandler(auth));
app.use("/api/tutors", tutorRouter);
app.use("/api/bookings", bookingRouter);
app.use("/api/categories", categoryRouter);
app.use("/api/reviews", reviewRouter);
app.get("/", (req, res) => {
  res.send("Hello Skill Bridge Backend!!!");
});
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
