// src/app.ts
import express from "express";
import { toNodeHandler } from "better-auth/node";

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.0",
  "engineVersion": "ab56fe763f921d033a6c195e7ddeb3e255bdbb57",
  "activeProvider": "postgresql",
  "inlineSchema": 'generator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel User {\n  id            String        @id\n  name          String\n  email         String        @unique\n  emailVerified Boolean       @default(false)\n  role          Role          @default(STUDENT)\n  image         String?\n  phone         String?\n  status        UserStatus    @default(ACTIVE)\n  createdAt     DateTime      @default(now())\n  updatedAt     DateTime      @updatedAt\n  tutor         TutorProfile?\n  accounts      Account[]\n  booking       Booking[]     @relation("StudentBookings")\n  review        Review[]\n  sessions      Session[]\n\n  @@map("user")\n}\n\nmodel TutorProfile {\n  id          String    @id @default(uuid())\n  bio         String?\n  hourlyRate  Int\n  experience  Int\n  availablity Boolean   @default(true)\n  categoryId  String\n  userId      String    @unique\n  createdAt   DateTime  @default(now())\n  updatedAt   DateTime  @updatedAt\n  category    Category  @relation(fields: [categoryId], references: [id])\n  user        User      @relation(fields: [userId], references: [id])\n  booking     Booking[] @relation("TutorBookings")\n  review      Review[]\n}\n\nmodel Category {\n  id    String         @id @default(uuid())\n  name  String         @unique\n  tutor TutorProfile[]\n\n  @@map("category")\n}\n\nmodel Booking {\n  id        String        @id @default(uuid())\n  date      DateTime\n  status    BookingStatus @default(PENDING)\n  createdAt DateTime      @default(now())\n  updatedAt DateTime      @updatedAt\n  tutorId   String\n  userId    String\n  tutor     TutorProfile  @relation("TutorBookings", fields: [tutorId], references: [id])\n  user      User          @relation("StudentBookings", fields: [userId], references: [id])\n  review    Review?\n\n  @@map("booking")\n}\n\nmodel Review {\n  id        String       @id @default(uuid())\n  rating    Int\n  comment   String?\n  tutorId   String\n  bookingId String       @unique\n  userId    String\n  createdAt DateTime     @default(now())\n  updatedAt DateTime     @updatedAt\n  booking   Booking      @relation(fields: [bookingId], references: [id])\n  tutor     TutorProfile @relation(fields: [tutorId], references: [id])\n  user      User         @relation(fields: [userId], references: [id])\n\n  @@map("review")\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String   @unique\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n\nenum BookingStatus {\n  PENDING\n  CONFIRMED\n  COMPLETED\n  CANCELLED\n}\n\nenum Role {\n  STUDENT\n  TUTOR\n  ADMIN\n}\n\nenum UserStatus {\n  ACTIVE\n  BANED\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"role","kind":"enum","type":"Role"},{"name":"image","kind":"scalar","type":"String"},{"name":"phone","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"UserStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"TutorProfileToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"booking","kind":"object","type":"Booking","relationName":"StudentBookings"},{"name":"review","kind":"object","type":"Review","relationName":"ReviewToUser"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"}],"dbName":"user"},"TutorProfile":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"bio","kind":"scalar","type":"String"},{"name":"hourlyRate","kind":"scalar","type":"Int"},{"name":"experience","kind":"scalar","type":"Int"},{"name":"availablity","kind":"scalar","type":"Boolean"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToTutorProfile"},{"name":"user","kind":"object","type":"User","relationName":"TutorProfileToUser"},{"name":"booking","kind":"object","type":"Booking","relationName":"TutorBookings"},{"name":"review","kind":"object","type":"Review","relationName":"ReviewToTutorProfile"}],"dbName":null},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"CategoryToTutorProfile"}],"dbName":"category"},"Booking":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"date","kind":"scalar","type":"DateTime"},{"name":"status","kind":"enum","type":"BookingStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"TutorBookings"},{"name":"user","kind":"object","type":"User","relationName":"StudentBookings"},{"name":"review","kind":"object","type":"Review","relationName":"BookingToReview"}],"dbName":"booking"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"bookingId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"booking","kind":"object","type":"Booking","relationName":"BookingToReview"},{"name":"tutor","kind":"object","type":"TutorProfile","relationName":"ReviewToTutorProfile"},{"name":"user","kind":"object","type":"User","relationName":"ReviewToUser"}],"dbName":"review"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","tutor","_count","category","user","booking","review","accounts","sessions","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","TutorProfile.findUnique","TutorProfile.findUniqueOrThrow","TutorProfile.findFirst","TutorProfile.findFirstOrThrow","TutorProfile.findMany","TutorProfile.createOne","TutorProfile.createMany","TutorProfile.createManyAndReturn","TutorProfile.updateOne","TutorProfile.updateMany","TutorProfile.updateManyAndReturn","TutorProfile.upsertOne","TutorProfile.deleteOne","TutorProfile.deleteMany","_avg","_sum","TutorProfile.groupBy","TutorProfile.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","Booking.groupBy","Booking.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","AND","OR","NOT","id","identifier","value","expiresAt","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","accountId","providerId","userId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","rating","comment","tutorId","bookingId","date","BookingStatus","status","name","every","some","none","bio","hourlyRate","experience","availablity","categoryId","email","emailVerified","Role","role","image","phone","UserStatus","is","isNot","connectOrCreate","upsert","disconnect","delete","connect","createMany","set","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "-QNIgAESAwAAiAIAIAcAAIoCACAIAACLAgAgCQAAiQIAIAoAAIwCACCTAQAAgwIAMJQBAAAjABCVAQAAgwIAMJYBAQAAAAGaAUAA4wEAIZsBQADjAQAhugEAAIcCywEiuwEBAOIBACHEAQEAAAABxQEgAIQCACHHAQAAhQLHASLIAQEAhgIAIckBAQCGAgAhAQAAAAEAIBAFAACZAgAgBgAAjgIAIAcAAIoCACAIAACLAgAgkwEAAJgCADCUAQAAAwAQlQEAAJgCADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIb8BAQCGAgAhwAECAJICACHBAQIAkgIAIcIBIACEAgAhwwEBAOIBACEBAAAAAwAgBQUAAMUDACAGAADCAwAgBwAAvwMAIAgAAMADACC_AQAAnwIAIBAFAACZAgAgBgAAjgIAIAcAAIoCACAIAACLAgAgkwEAAJgCADCUAQAAAwAQlQEAAJgCADCWAQEAAAABmgFAAOMBACGbAUAA4wEAIakBAQAAAAG_AQEAhgIAIcABAgCSAgAhwQECAJICACHCASAAhAIAIcMBAQDiAQAhAwAAAAMAIAEAAAUAMAIAAAYAIAEAAAADACANAwAAlAIAIAYAAI4CACAIAACXAgAgkwEAAJUCADCUAQAACQAQlQEAAJUCADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbYBAQDiAQAhuAFAAOMBACG6AQAAlgK6ASIDAwAAvQMAIAYAAMIDACAIAADEAwAgDQMAAJQCACAGAACOAgAgCAAAlwIAIJMBAACVAgAwlAEAAAkAEJUBAACVAgAwlgEBAAAAAZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbYBAQDiAQAhuAFAAOMBACG6AQAAlgK6ASIDAAAACQAgAQAACgAwAgAACwAgDgMAAJQCACAGAACOAgAgBwAAkwIAIJMBAACRAgAwlAEAAA0AEJUBAACRAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG0AQIAkgIAIbUBAQCGAgAhtgEBAOIBACG3AQEA4gEAIQEAAAANACAEAwAAvQMAIAYAAMIDACAHAADDAwAgtQEAAJ8CACAOAwAAlAIAIAYAAI4CACAHAACTAgAgkwEAAJECADCUAQAADQAQlQEAAJECADCWAQEAAAABmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhtAECAJICACG1AQEAhgIAIbYBAQDiAQAhtwEBAAAAAQMAAAANACABAAAPADACAAAQACABAAAACQAgAQAAAA0AIBEGAACOAgAgkwEAAI8CADCUAQAAFAAQlQEAAI8CADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGnAQEA4gEAIagBAQDiAQAhqQEBAOIBACGqAQEAhgIAIasBAQCGAgAhrAEBAIYCACGtAUAAkAIAIa4BQACQAgAhrwEBAIYCACGwAQEAhgIAIQgGAADCAwAgqgEAAJ8CACCrAQAAnwIAIKwBAACfAgAgrQEAAJ8CACCuAQAAnwIAIK8BAACfAgAgsAEAAJ8CACARBgAAjgIAIJMBAACPAgAwlAEAABQAEJUBAACPAgAwlgEBAAAAAZoBQADjAQAhmwFAAOMBACGnAQEA4gEAIagBAQDiAQAhqQEBAOIBACGqAQEAhgIAIasBAQCGAgAhrAEBAIYCACGtAUAAkAIAIa4BQACQAgAhrwEBAIYCACGwAQEAhgIAIQMAAAAUACABAAAVADACAAAWACADAAAACQAgAQAACgAwAgAACwAgAwAAAA0AIAEAAA8AMAIAABAAIAwGAACOAgAgkwEAAI0CADCUAQAAGgAQlQEAAI0CADCWAQEA4gEAIZkBQADjAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhsQEBAOIBACGyAQEAhgIAIbMBAQCGAgAhAwYAAMIDACCyAQAAnwIAILMBAACfAgAgDAYAAI4CACCTAQAAjQIAMJQBAAAaABCVAQAAjQIAMJYBAQAAAAGZAUAA4wEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbEBAQAAAAGyAQEAhgIAIbMBAQCGAgAhAwAAABoAIAEAABsAMAIAABwAIAEAAAAUACABAAAACQAgAQAAAA0AIAEAAAAaACABAAAAAQAgEgMAAIgCACAHAACKAgAgCAAAiwIAIAkAAIkCACAKAACMAgAgkwEAAIMCADCUAQAAIwAQlQEAAIMCADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACG6AQAAhwLLASK7AQEA4gEAIcQBAQDiAQAhxQEgAIQCACHHAQAAhQLHASLIAQEAhgIAIckBAQCGAgAhBwMAAL0DACAHAAC_AwAgCAAAwAMAIAkAAL4DACAKAADBAwAgyAEAAJ8CACDJAQAAnwIAIAMAAAAjACABAAAkADACAAABACADAAAAIwAgAQAAJAAwAgAAAQAgAwAAACMAIAEAACQAMAIAAAEAIA8DAAC4AwAgBwAAugMAIAgAALsDACAJAAC5AwAgCgAAvAMAIJYBAQAAAAGaAUAAAAABmwFAAAAAAboBAAAAywECuwEBAAAAAcQBAQAAAAHFASAAAAABxwEAAADHAQLIAQEAAAAByQEBAAAAAQEQAAAoACAKlgEBAAAAAZoBQAAAAAGbAUAAAAABugEAAADLAQK7AQEAAAABxAEBAAAAAcUBIAAAAAHHAQAAAMcBAsgBAQAAAAHJAQEAAAABARAAACoAMAEQAAAqADAPAwAAhAMAIAcAAIYDACAIAACHAwAgCQAAhQMAIAoAAIgDACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG6AQAAgwPLASK7AQEAnQIAIcQBAQCdAgAhxQEgANUCACHHAQAAggPHASLIAQEAowIAIckBAQCjAgAhAgAAAAEAIBAAAC0AIAqWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG6AQAAgwPLASK7AQEAnQIAIcQBAQCdAgAhxQEgANUCACHHAQAAggPHASLIAQEAowIAIckBAQCjAgAhAgAAACMAIBAAAC8AIAIAAAAjACAQAAAvACADAAAAAQAgFwAAKAAgGAAALQAgAQAAAAEAIAEAAAAjACAFBAAA_wIAIB0AAIEDACAeAACAAwAgyAEAAJ8CACDJAQAAnwIAIA2TAQAA_AEAMJQBAAA2ABCVAQAA_AEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIboBAAD-AcsBIrsBAQDaAQAhxAEBANoBACHFASAA-QEAIccBAAD9AccBIsgBAQDlAQAhyQEBAOUBACEDAAAAIwAgAQAANQAwHAAANgAgAwAAACMAIAEAACQAMAIAAAEAIAEAAAAGACABAAAABgAgAwAAAAMAIAEAAAUAMAIAAAYAIAMAAAADACABAAAFADACAAAGACADAAAAAwAgAQAABQAwAgAABgAgDQUAAP4CACAGAADzAgAgBwAA9AIAIAgAAPUCACCWAQEAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABvwEBAAAAAcABAgAAAAHBAQIAAAABwgEgAAAAAcMBAQAAAAEBEAAAPgAgCZYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG_AQEAAAABwAECAAAAAcEBAgAAAAHCASAAAAABwwEBAAAAAQEQAABAADABEAAAQAAwDQUAAP0CACAGAADXAgAgBwAA2AIAIAgAANkCACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIb8BAQCjAgAhwAECALECACHBAQIAsQIAIcIBIADVAgAhwwEBAJ0CACECAAAABgAgEAAAQwAgCZYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhvwEBAKMCACHAAQIAsQIAIcEBAgCxAgAhwgEgANUCACHDAQEAnQIAIQIAAAADACAQAABFACACAAAAAwAgEAAARQAgAwAAAAYAIBcAAD4AIBgAAEMAIAEAAAAGACABAAAAAwAgBgQAAPgCACAdAAD7AgAgHgAA-gIAIC8AAPkCACAwAAD8AgAgvwEAAJ8CACAMkwEAAPgBADCUAQAATAAQlQEAAPgBADCWAQEA2gEAIZoBQADbAQAhmwFAANsBACGpAQEA2gEAIb8BAQDlAQAhwAECAO4BACHBAQIA7gEAIcIBIAD5AQAhwwEBANoBACEDAAAAAwAgAQAASwAwHAAATAAgAwAAAAMAIAEAAAUAMAIAAAYAIAYDAAD3AQAgkwEAAPYBADCUAQAAUgAQlQEAAPYBADCWAQEAAAABuwEBAAAAAQEAAABPACABAAAATwAgBgMAAPcBACCTAQAA9gEAMJQBAABSABCVAQAA9gEAMJYBAQDiAQAhuwEBAOIBACEBAwAA9wIAIAMAAABSACABAABTADACAABPACADAAAAUgAgAQAAUwAwAgAATwAgAwAAAFIAIAEAAFMAMAIAAE8AIAMDAAD2AgAglgEBAAAAAbsBAQAAAAEBEAAAVwAgApYBAQAAAAG7AQEAAAABARAAAFkAMAEQAABZADADAwAAygIAIJYBAQCdAgAhuwEBAJ0CACECAAAATwAgEAAAXAAgApYBAQCdAgAhuwEBAJ0CACECAAAAUgAgEAAAXgAgAgAAAFIAIBAAAF4AIAMAAABPACAXAABXACAYAABcACABAAAATwAgAQAAAFIAIAMEAADHAgAgHQAAyQIAIB4AAMgCACAFkwEAAPUBADCUAQAAZQAQlQEAAPUBADCWAQEA2gEAIbsBAQDaAQAhAwAAAFIAIAEAAGQAMBwAAGUAIAMAAABSACABAABTADACAABPACABAAAACwAgAQAAAAsAIAMAAAAJACABAAAKADACAAALACADAAAACQAgAQAACgAwAgAACwAgAwAAAAkAIAEAAAoAMAIAAAsAIAoDAADEAgAgBgAAxQIAIAgAAMYCACCWAQEAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABtgEBAAAAAbgBQAAAAAG6AQAAALoBAgEQAABtACAHlgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbYBAQAAAAG4AUAAAAABugEAAAC6AQIBEAAAbwAwARAAAG8AMAoDAAC8AgAgBgAAvQIAIAgAAL4CACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbYBAQCdAgAhuAFAAJ4CACG6AQAAuwK6ASICAAAACwAgEAAAcgAgB5YBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhtgEBAJ0CACG4AUAAngIAIboBAAC7AroBIgIAAAAJACAQAAB0ACACAAAACQAgEAAAdAAgAwAAAAsAIBcAAG0AIBgAAHIAIAEAAAALACABAAAACQAgAwQAALgCACAdAAC6AgAgHgAAuQIAIAqTAQAA8QEAMJQBAAB7ABCVAQAA8QEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIakBAQDaAQAhtgEBANoBACG4AUAA2wEAIboBAADyAboBIgMAAAAJACABAAB6ADAcAAB7ACADAAAACQAgAQAACgAwAgAACwAgAQAAABAAIAEAAAAQACADAAAADQAgAQAADwAwAgAAEAAgAwAAAA0AIAEAAA8AMAIAABAAIAMAAAANACABAAAPADACAAAQACALAwAAtgIAIAYAALcCACAHAAC1AgAglgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbQBAgAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAEBEAAAgwEAIAiWAQEAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABtAECAAAAAbUBAQAAAAG2AQEAAAABtwEBAAAAAQEQAACFAQAwARAAAIUBADALAwAAswIAIAYAALQCACAHAACyAgAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhqQEBAJ0CACG0AQIAsQIAIbUBAQCjAgAhtgEBAJ0CACG3AQEAnQIAIQIAAAAQACAQAACIAQAgCJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhtAECALECACG1AQEAowIAIbYBAQCdAgAhtwEBAJ0CACECAAAADQAgEAAAigEAIAIAAAANACAQAACKAQAgAwAAABAAIBcAAIMBACAYAACIAQAgAQAAABAAIAEAAAANACAGBAAArAIAIB0AAK8CACAeAACuAgAgLwAArQIAIDAAALACACC1AQAAnwIAIAuTAQAA7QEAMJQBAACRAQAQlQEAAO0BADCWAQEA2gEAIZoBQADbAQAhmwFAANsBACGpAQEA2gEAIbQBAgDuAQAhtQEBAOUBACG2AQEA2gEAIbcBAQDaAQAhAwAAAA0AIAEAAJABADAcAACRAQAgAwAAAA0AIAEAAA8AMAIAABAAIAEAAAAcACABAAAAHAAgAwAAABoAIAEAABsAMAIAABwAIAMAAAAaACABAAAbADACAAAcACADAAAAGgAgAQAAGwAwAgAAHAAgCQYAAKsCACCWAQEAAAABmQFAAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbEBAQAAAAGyAQEAAAABswEBAAAAAQEQAACZAQAgCJYBAQAAAAGZAUAAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABsQEBAAAAAbIBAQAAAAGzAQEAAAABARAAAJsBADABEAAAmwEAMAkGAACqAgAglgEBAJ0CACGZAUAAngIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbEBAQCdAgAhsgEBAKMCACGzAQEAowIAIQIAAAAcACAQAACeAQAgCJYBAQCdAgAhmQFAAJ4CACGaAUAAngIAIZsBQACeAgAhqQEBAJ0CACGxAQEAnQIAIbIBAQCjAgAhswEBAKMCACECAAAAGgAgEAAAoAEAIAIAAAAaACAQAACgAQAgAwAAABwAIBcAAJkBACAYAACeAQAgAQAAABwAIAEAAAAaACAFBAAApwIAIB0AAKkCACAeAACoAgAgsgEAAJ8CACCzAQAAnwIAIAuTAQAA7AEAMJQBAACnAQAQlQEAAOwBADCWAQEA2gEAIZkBQADbAQAhmgFAANsBACGbAUAA2wEAIakBAQDaAQAhsQEBANoBACGyAQEA5QEAIbMBAQDlAQAhAwAAABoAIAEAAKYBADAcAACnAQAgAwAAABoAIAEAABsAMAIAABwAIAEAAAAWACABAAAAFgAgAwAAABQAIAEAABUAMAIAABYAIAMAAAAUACABAAAVADACAAAWACADAAAAFAAgAQAAFQAwAgAAFgAgDgYAAKYCACCWAQEAAAABmgFAAAAAAZsBQAAAAAGnAQEAAAABqAEBAAAAAakBAQAAAAGqAQEAAAABqwEBAAAAAawBAQAAAAGtAUAAAAABrgFAAAAAAa8BAQAAAAGwAQEAAAABARAAAK8BACANlgEBAAAAAZoBQAAAAAGbAUAAAAABpwEBAAAAAagBAQAAAAGpAQEAAAABqgEBAAAAAasBAQAAAAGsAQEAAAABrQFAAAAAAa4BQAAAAAGvAQEAAAABsAEBAAAAAQEQAACxAQAwARAAALEBADAOBgAApQIAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIacBAQCdAgAhqAEBAJ0CACGpAQEAnQIAIaoBAQCjAgAhqwEBAKMCACGsAQEAowIAIa0BQACkAgAhrgFAAKQCACGvAQEAowIAIbABAQCjAgAhAgAAABYAIBAAALQBACANlgEBAJ0CACGaAUAAngIAIZsBQACeAgAhpwEBAJ0CACGoAQEAnQIAIakBAQCdAgAhqgEBAKMCACGrAQEAowIAIawBAQCjAgAhrQFAAKQCACGuAUAApAIAIa8BAQCjAgAhsAEBAKMCACECAAAAFAAgEAAAtgEAIAIAAAAUACAQAAC2AQAgAwAAABYAIBcAAK8BACAYAAC0AQAgAQAAABYAIAEAAAAUACAKBAAAoAIAIB0AAKICACAeAAChAgAgqgEAAJ8CACCrAQAAnwIAIKwBAACfAgAgrQEAAJ8CACCuAQAAnwIAIK8BAACfAgAgsAEAAJ8CACAQkwEAAOQBADCUAQAAvQEAEJUBAADkAQAwlgEBANoBACGaAUAA2wEAIZsBQADbAQAhpwEBANoBACGoAQEA2gEAIakBAQDaAQAhqgEBAOUBACGrAQEA5QEAIawBAQDlAQAhrQFAAOYBACGuAUAA5gEAIa8BAQDlAQAhsAEBAOUBACEDAAAAFAAgAQAAvAEAMBwAAL0BACADAAAAFAAgAQAAFQAwAgAAFgAgCZMBAADhAQAwlAEAAMMBABCVAQAA4QEAMJYBAQAAAAGXAQEA4gEAIZgBAQDiAQAhmQFAAOMBACGaAUAA4wEAIZsBQADjAQAhAQAAAMABACABAAAAwAEAIAmTAQAA4QEAMJQBAADDAQAQlQEAAOEBADCWAQEA4gEAIZcBAQDiAQAhmAEBAOIBACGZAUAA4wEAIZoBQADjAQAhmwFAAOMBACEAAwAAAMMBACABAADEAQAwAgAAwAEAIAMAAADDAQAgAQAAxAEAMAIAAMABACADAAAAwwEAIAEAAMQBADACAADAAQAgBpYBAQAAAAGXAQEAAAABmAEBAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAQEQAADIAQAgBpYBAQAAAAGXAQEAAAABmAEBAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAQEQAADKAQAwARAAAMoBADAGlgEBAJ0CACGXAQEAnQIAIZgBAQCdAgAhmQFAAJ4CACGaAUAAngIAIZsBQACeAgAhAgAAAMABACAQAADNAQAgBpYBAQCdAgAhlwEBAJ0CACGYAQEAnQIAIZkBQACeAgAhmgFAAJ4CACGbAUAAngIAIQIAAADDAQAgEAAAzwEAIAIAAADDAQAgEAAAzwEAIAMAAADAAQAgFwAAyAEAIBgAAM0BACABAAAAwAEAIAEAAADDAQAgAwQAAJoCACAdAACcAgAgHgAAmwIAIAmTAQAA2QEAMJQBAADWAQAQlQEAANkBADCWAQEA2gEAIZcBAQDaAQAhmAEBANoBACGZAUAA2wEAIZoBQADbAQAhmwFAANsBACEDAAAAwwEAIAEAANUBADAcAADWAQAgAwAAAMMBACABAADEAQAwAgAAwAEAIAmTAQAA2QEAMJQBAADWAQAQlQEAANkBADCWAQEA2gEAIZcBAQDaAQAhmAEBANoBACGZAUAA2wEAIZoBQADbAQAhmwFAANsBACEOBAAA3QEAIB0AAOABACAeAADgAQAgnAEBAAAAAZ0BAQAAAASeAQEAAAAEnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBAQDfAQAhpAEBAAAAAaUBAQAAAAGmAQEAAAABCwQAAN0BACAdAADeAQAgHgAA3gEAIJwBQAAAAAGdAUAAAAAEngFAAAAABJ8BQAAAAAGgAUAAAAABoQFAAAAAAaIBQAAAAAGjAUAA3AEAIQsEAADdAQAgHQAA3gEAIB4AAN4BACCcAUAAAAABnQFAAAAABJ4BQAAAAASfAUAAAAABoAFAAAAAAaEBQAAAAAGiAUAAAAABowFAANwBACEInAECAAAAAZ0BAgAAAASeAQIAAAAEnwECAAAAAaABAgAAAAGhAQIAAAABogECAAAAAaMBAgDdAQAhCJwBQAAAAAGdAUAAAAAEngFAAAAABJ8BQAAAAAGgAUAAAAABoQFAAAAAAaIBQAAAAAGjAUAA3gEAIQ4EAADdAQAgHQAA4AEAIB4AAOABACCcAQEAAAABnQEBAAAABJ4BAQAAAASfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEBAN8BACGkAQEAAAABpQEBAAAAAaYBAQAAAAELnAEBAAAAAZ0BAQAAAASeAQEAAAAEnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBAQDgAQAhpAEBAAAAAaUBAQAAAAGmAQEAAAABCZMBAADhAQAwlAEAAMMBABCVAQAA4QEAMJYBAQDiAQAhlwEBAOIBACGYAQEA4gEAIZkBQADjAQAhmgFAAOMBACGbAUAA4wEAIQucAQEAAAABnQEBAAAABJ4BAQAAAASfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEBAOABACGkAQEAAAABpQEBAAAAAaYBAQAAAAEInAFAAAAAAZ0BQAAAAASeAUAAAAAEnwFAAAAAAaABQAAAAAGhAUAAAAABogFAAAAAAaMBQADeAQAhEJMBAADkAQAwlAEAAL0BABCVAQAA5AEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIacBAQDaAQAhqAEBANoBACGpAQEA2gEAIaoBAQDlAQAhqwEBAOUBACGsAQEA5QEAIa0BQADmAQAhrgFAAOYBACGvAQEA5QEAIbABAQDlAQAhDgQAAOgBACAdAADrAQAgHgAA6wEAIJwBAQAAAAGdAQEAAAAFngEBAAAABZ8BAQAAAAGgAQEAAAABoQEBAAAAAaIBAQAAAAGjAQEA6gEAIaQBAQAAAAGlAQEAAAABpgEBAAAAAQsEAADoAQAgHQAA6QEAIB4AAOkBACCcAUAAAAABnQFAAAAABZ4BQAAAAAWfAUAAAAABoAFAAAAAAaEBQAAAAAGiAUAAAAABowFAAOcBACELBAAA6AEAIB0AAOkBACAeAADpAQAgnAFAAAAAAZ0BQAAAAAWeAUAAAAAFnwFAAAAAAaABQAAAAAGhAUAAAAABogFAAAAAAaMBQADnAQAhCJwBAgAAAAGdAQIAAAAFngECAAAABZ8BAgAAAAGgAQIAAAABoQECAAAAAaIBAgAAAAGjAQIA6AEAIQicAUAAAAABnQFAAAAABZ4BQAAAAAWfAUAAAAABoAFAAAAAAaEBQAAAAAGiAUAAAAABowFAAOkBACEOBAAA6AEAIB0AAOsBACAeAADrAQAgnAEBAAAAAZ0BAQAAAAWeAQEAAAAFnwEBAAAAAaABAQAAAAGhAQEAAAABogEBAAAAAaMBAQDqAQAhpAEBAAAAAaUBAQAAAAGmAQEAAAABC5wBAQAAAAGdAQEAAAAFngEBAAAABZ8BAQAAAAGgAQEAAAABoQEBAAAAAaIBAQAAAAGjAQEA6wEAIaQBAQAAAAGlAQEAAAABpgEBAAAAAQuTAQAA7AEAMJQBAACnAQAQlQEAAOwBADCWAQEA2gEAIZkBQADbAQAhmgFAANsBACGbAUAA2wEAIakBAQDaAQAhsQEBANoBACGyAQEA5QEAIbMBAQDlAQAhC5MBAADtAQAwlAEAAJEBABCVAQAA7QEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIakBAQDaAQAhtAECAO4BACG1AQEA5QEAIbYBAQDaAQAhtwEBANoBACENBAAA3QEAIB0AAN0BACAeAADdAQAgLwAA8AEAIDAAAN0BACCcAQIAAAABnQECAAAABJ4BAgAAAASfAQIAAAABoAECAAAAAaEBAgAAAAGiAQIAAAABowECAO8BACENBAAA3QEAIB0AAN0BACAeAADdAQAgLwAA8AEAIDAAAN0BACCcAQIAAAABnQECAAAABJ4BAgAAAASfAQIAAAABoAECAAAAAaEBAgAAAAGiAQIAAAABowECAO8BACEInAEIAAAAAZ0BCAAAAASeAQgAAAAEnwEIAAAAAaABCAAAAAGhAQgAAAABogEIAAAAAaMBCADwAQAhCpMBAADxAQAwlAEAAHsAEJUBAADxAQAwlgEBANoBACGaAUAA2wEAIZsBQADbAQAhqQEBANoBACG2AQEA2gEAIbgBQADbAQAhugEAAPIBugEiBwQAAN0BACAdAAD0AQAgHgAA9AEAIJwBAAAAugECnQEAAAC6AQieAQAAALoBCKMBAADzAboBIgcEAADdAQAgHQAA9AEAIB4AAPQBACCcAQAAALoBAp0BAAAAugEIngEAAAC6AQijAQAA8wG6ASIEnAEAAAC6AQKdAQAAALoBCJ4BAAAAugEIowEAAPQBugEiBZMBAAD1AQAwlAEAAGUAEJUBAAD1AQAwlgEBANoBACG7AQEA2gEAIQYDAAD3AQAgkwEAAPYBADCUAQAAUgAQlQEAAPYBADCWAQEA4gEAIbsBAQDiAQAhA7wBAAADACC9AQAAAwAgvgEAAAMAIAyTAQAA-AEAMJQBAABMABCVAQAA-AEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIakBAQDaAQAhvwEBAOUBACHAAQIA7gEAIcEBAgDuAQAhwgEgAPkBACHDAQEA2gEAIQUEAADdAQAgHQAA-wEAIB4AAPsBACCcASAAAAABowEgAPoBACEFBAAA3QEAIB0AAPsBACAeAAD7AQAgnAEgAAAAAaMBIAD6AQAhApwBIAAAAAGjASAA-wEAIQ2TAQAA_AEAMJQBAAA2ABCVAQAA_AEAMJYBAQDaAQAhmgFAANsBACGbAUAA2wEAIboBAAD-AcsBIrsBAQDaAQAhxAEBANoBACHFASAA-QEAIccBAAD9AccBIsgBAQDlAQAhyQEBAOUBACEHBAAA3QEAIB0AAIICACAeAACCAgAgnAEAAADHAQKdAQAAAMcBCJ4BAAAAxwEIowEAAIECxwEiBwQAAN0BACAdAACAAgAgHgAAgAIAIJwBAAAAywECnQEAAADLAQieAQAAAMsBCKMBAAD_AcsBIgcEAADdAQAgHQAAgAIAIB4AAIACACCcAQAAAMsBAp0BAAAAywEIngEAAADLAQijAQAA_wHLASIEnAEAAADLAQKdAQAAAMsBCJ4BAAAAywEIowEAAIACywEiBwQAAN0BACAdAACCAgAgHgAAggIAIJwBAAAAxwECnQEAAADHAQieAQAAAMcBCKMBAACBAscBIgScAQAAAMcBAp0BAAAAxwEIngEAAADHAQijAQAAggLHASISAwAAiAIAIAcAAIoCACAIAACLAgAgCQAAiQIAIAoAAIwCACCTAQAAgwIAMJQBAAAjABCVAQAAgwIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIboBAACHAssBIrsBAQDiAQAhxAEBAOIBACHFASAAhAIAIccBAACFAscBIsgBAQCGAgAhyQEBAIYCACECnAEgAAAAAaMBIAD7AQAhBJwBAAAAxwECnQEAAADHAQieAQAAAMcBCKMBAACCAscBIgucAQEAAAABnQEBAAAABZ4BAQAAAAWfAQEAAAABoAEBAAAAAaEBAQAAAAGiAQEAAAABowEBAOsBACGkAQEAAAABpQEBAAAAAaYBAQAAAAEEnAEAAADLAQKdAQAAAMsBCJ4BAAAAywEIowEAAIACywEiEgUAAJkCACAGAACOAgAgBwAAigIAIAgAAIsCACCTAQAAmAIAMJQBAAADABCVAQAAmAIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhvwEBAIYCACHAAQIAkgIAIcEBAgCSAgAhwgEgAIQCACHDAQEA4gEAIcsBAAADACDMAQAAAwAgA7wBAAAUACC9AQAAFAAgvgEAABQAIAO8AQAACQAgvQEAAAkAIL4BAAAJACADvAEAAA0AIL0BAAANACC-AQAADQAgA7wBAAAaACC9AQAAGgAgvgEAABoAIAwGAACOAgAgkwEAAI0CADCUAQAAGgAQlQEAAI0CADCWAQEA4gEAIZkBQADjAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhsQEBAOIBACGyAQEAhgIAIbMBAQCGAgAhFAMAAIgCACAHAACKAgAgCAAAiwIAIAkAAIkCACAKAACMAgAgkwEAAIMCADCUAQAAIwAQlQEAAIMCADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACG6AQAAhwLLASK7AQEA4gEAIcQBAQDiAQAhxQEgAIQCACHHAQAAhQLHASLIAQEAhgIAIckBAQCGAgAhywEAACMAIMwBAAAjACARBgAAjgIAIJMBAACPAgAwlAEAABQAEJUBAACPAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhpwEBAOIBACGoAQEA4gEAIakBAQDiAQAhqgEBAIYCACGrAQEAhgIAIawBAQCGAgAhrQFAAJACACGuAUAAkAIAIa8BAQCGAgAhsAEBAIYCACEInAFAAAAAAZ0BQAAAAAWeAUAAAAAFnwFAAAAAAaABQAAAAAGhAUAAAAABogFAAAAAAaMBQADpAQAhDgMAAJQCACAGAACOAgAgBwAAkwIAIJMBAACRAgAwlAEAAA0AEJUBAACRAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG0AQIAkgIAIbUBAQCGAgAhtgEBAOIBACG3AQEA4gEAIQicAQIAAAABnQECAAAABJ4BAgAAAASfAQIAAAABoAECAAAAAaEBAgAAAAGiAQIAAAABowECAN0BACEPAwAAlAIAIAYAAI4CACAIAACXAgAgkwEAAJUCADCUAQAACQAQlQEAAJUCADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbYBAQDiAQAhuAFAAOMBACG6AQAAlgK6ASLLAQAACQAgzAEAAAkAIBIFAACZAgAgBgAAjgIAIAcAAIoCACAIAACLAgAgkwEAAJgCADCUAQAAAwAQlQEAAJgCADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIb8BAQCGAgAhwAECAJICACHBAQIAkgIAIcIBIACEAgAhwwEBAOIBACHLAQAAAwAgzAEAAAMAIA0DAACUAgAgBgAAjgIAIAgAAJcCACCTAQAAlQIAMJQBAAAJABCVAQAAlQIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhtgEBAOIBACG4AUAA4wEAIboBAACWAroBIgScAQAAALoBAp0BAAAAugEIngEAAAC6AQijAQAA9AG6ASIQAwAAlAIAIAYAAI4CACAHAACTAgAgkwEAAJECADCUAQAADQAQlQEAAJECADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbQBAgCSAgAhtQEBAIYCACG2AQEA4gEAIbcBAQDiAQAhywEAAA0AIMwBAAANACAQBQAAmQIAIAYAAI4CACAHAACKAgAgCAAAiwIAIJMBAACYAgAwlAEAAAMAEJUBAACYAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG_AQEAhgIAIcABAgCSAgAhwQECAJICACHCASAAhAIAIcMBAQDiAQAhCAMAAPcBACCTAQAA9gEAMJQBAABSABCVAQAA9gEAMJYBAQDiAQAhuwEBAOIBACHLAQAAUgAgzAEAAFIAIAAAAAHTAQEAAAABAdMBQAAAAAEAAAAAAdMBAQAAAAEB0wFAAAAAAQUXAAD1AwAgGAAA-AMAIM0BAAD2AwAgzgEAAPcDACDRAQAAAQAgAxcAAPUDACDNAQAA9gMAINEBAAABACAAAAAFFwAA8AMAIBgAAPMDACDNAQAA8QMAIM4BAADyAwAg0QEAAAEAIAMXAADwAwAgzQEAAPEDACDRAQAAAQAgAAAAAAAF0wECAAAAAdYBAgAAAAHXAQIAAAAB2AECAAAAAdkBAgAAAAEFFwAA5QMAIBgAAO4DACDNAQAA5gMAIM4BAADtAwAg0QEAAAsAIAUXAADjAwAgGAAA6wMAIM0BAADkAwAgzgEAAOoDACDRAQAABgAgBRcAAOEDACAYAADoAwAgzQEAAOIDACDOAQAA5wMAINEBAAABACADFwAA5QMAIM0BAADmAwAg0QEAAAsAIAMXAADjAwAgzQEAAOQDACDRAQAABgAgAxcAAOEDACDNAQAA4gMAINEBAAABACAAAAAB0wEAAAC6AQIFFwAA2QMAIBgAAN8DACDNAQAA2gMAIM4BAADeAwAg0QEAAAYAIAUXAADXAwAgGAAA3AMAIM0BAADYAwAgzgEAANsDACDRAQAAAQAgBxcAAL8CACAYAADCAgAgzQEAAMACACDOAQAAwQIAIM8BAAANACDQAQAADQAg0QEAABAAIAkDAAC2AgAgBgAAtwIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG0AQIAAAABtQEBAAAAAbYBAQAAAAECAAAAEAAgFwAAvwIAIAMAAAANACAXAAC_AgAgGAAAwwIAIAsAAAANACADAACzAgAgBgAAtAIAIBAAAMMCACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbQBAgCxAgAhtQEBAKMCACG2AQEAnQIAIQkDAACzAgAgBgAAtAIAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhtAECALECACG1AQEAowIAIbYBAQCdAgAhAxcAANkDACDNAQAA2gMAINEBAAAGACADFwAA1wMAIM0BAADYAwAg0QEAAAEAIAMXAAC_AgAgzQEAAMACACDRAQAAEAAgAAAACxcAAMsCADAYAADQAgAwzQEAAMwCADDOAQAAzQIAMM8BAADPAgAw0AEAAM8CADDRAQAAzwIAMNIBAADOAgAg0wEAAM8CADDUAQAA0QIAMNUBAADSAgAwCwYAAPMCACAHAAD0AgAgCAAA9QIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG_AQEAAAABwAECAAAAAcEBAgAAAAHCASAAAAABAgAAAAYAIBcAAPICACADAAAABgAgFwAA8gIAIBgAANYCACABEAAA1gMAMBAFAACZAgAgBgAAjgIAIAcAAIoCACAIAACLAgAgkwEAAJgCADCUAQAAAwAQlQEAAJgCADCWAQEAAAABmgFAAOMBACGbAUAA4wEAIakBAQAAAAG_AQEAhgIAIcABAgCSAgAhwQECAJICACHCASAAhAIAIcMBAQDiAQAhAgAAAAYAIBAAANYCACACAAAA0wIAIBAAANQCACAMkwEAANICADCUAQAA0wIAEJUBAADSAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG_AQEAhgIAIcABAgCSAgAhwQECAJICACHCASAAhAIAIcMBAQDiAQAhDJMBAADSAgAwlAEAANMCABCVAQAA0gIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhvwEBAIYCACHAAQIAkgIAIcEBAgCSAgAhwgEgAIQCACHDAQEA4gEAIQiWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIb8BAQCjAgAhwAECALECACHBAQIAsQIAIcIBIADVAgAhAdMBIAAAAAELBgAA1wIAIAcAANgCACAIAADZAgAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhqQEBAJ0CACG_AQEAowIAIcABAgCxAgAhwQECALECACHCASAA1QIAIQUXAADPAwAgGAAA1AMAIM0BAADQAwAgzgEAANMDACDRAQAAAQAgCxcAAOYCADAYAADrAgAwzQEAAOcCADDOAQAA6AIAMM8BAADqAgAw0AEAAOoCADDRAQAA6gIAMNIBAADpAgAg0wEAAOoCADDUAQAA7AIAMNUBAADtAgAwCxcAANoCADAYAADfAgAwzQEAANsCADDOAQAA3AIAMM8BAADeAgAw0AEAAN4CADDRAQAA3gIAMNIBAADdAgAg0wEAAN4CADDUAQAA4AIAMNUBAADhAgAwCQYAALcCACAHAAC1AgAglgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbQBAgAAAAG1AQEAAAABtwEBAAAAAQIAAAAQACAXAADlAgAgAwAAABAAIBcAAOUCACAYAADkAgAgARAAANIDADAOAwAAlAIAIAYAAI4CACAHAACTAgAgkwEAAJECADCUAQAADQAQlQEAAJECADCWAQEAAAABmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhtAECAJICACG1AQEAhgIAIbYBAQDiAQAhtwEBAAAAAQIAAAAQACAQAADkAgAgAgAAAOICACAQAADjAgAgC5MBAADhAgAwlAEAAOICABCVAQAA4QIAMJYBAQDiAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhtAECAJICACG1AQEAhgIAIbYBAQDiAQAhtwEBAOIBACELkwEAAOECADCUAQAA4gIAEJUBAADhAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG0AQIAkgIAIbUBAQCGAgAhtgEBAOIBACG3AQEA4gEAIQeWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbQBAgCxAgAhtQEBAKMCACG3AQEAnQIAIQkGAAC0AgAgBwAAsgIAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhtAECALECACG1AQEAowIAIbcBAQCdAgAhCQYAALcCACAHAAC1AgAglgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbQBAgAAAAG1AQEAAAABtwEBAAAAAQgGAADFAgAgCAAAxgIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG4AUAAAAABugEAAAC6AQICAAAACwAgFwAA8QIAIAMAAAALACAXAADxAgAgGAAA8AIAIAEQAADRAwAwDQMAAJQCACAGAACOAgAgCAAAlwIAIJMBAACVAgAwlAEAAAkAEJUBAACVAgAwlgEBAAAAAZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbYBAQDiAQAhuAFAAOMBACG6AQAAlgK6ASICAAAACwAgEAAA8AIAIAIAAADuAgAgEAAA7wIAIAqTAQAA7QIAMJQBAADuAgAQlQEAAO0CADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGpAQEA4gEAIbYBAQDiAQAhuAFAAOMBACG6AQAAlgK6ASIKkwEAAO0CADCUAQAA7gIAEJUBAADtAgAwlgEBAOIBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACG2AQEA4gEAIbgBQADjAQAhugEAAJYCugEiBpYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhuAFAAJ4CACG6AQAAuwK6ASIIBgAAvQIAIAgAAL4CACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbgBQACeAgAhugEAALsCugEiCAYAAMUCACAIAADGAgAglgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbgBQAAAAAG6AQAAALoBAgsGAADzAgAgBwAA9AIAIAgAAPUCACCWAQEAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABvwEBAAAAAcABAgAAAAHBAQIAAAABwgEgAAAAAQMXAADPAwAgzQEAANADACDRAQAAAQAgBBcAAOYCADDNAQAA5wIAMNEBAADqAgAw0gEAAOkCACAEFwAA2gIAMM0BAADbAgAw0QEAAN4CADDSAQAA3QIAIAQXAADLAgAwzQEAAMwCADDRAQAAzwIAMNIBAADOAgAgAAAAAAAABRcAAMoDACAYAADNAwAgzQEAAMsDACDOAQAAzAMAINEBAABPACADFwAAygMAIM0BAADLAwAg0QEAAE8AIAAAAAHTAQAAAMcBAgHTAQAAAMsBAgcXAACzAwAgGAAAtgMAIM0BAAC0AwAgzgEAALUDACDPAQAAAwAg0AEAAAMAINEBAAAGACALFwAApwMAMBgAAKwDADDNAQAAqAMAMM4BAACpAwAwzwEAAKsDADDQAQAAqwMAMNEBAACrAwAw0gEAAKoDACDTAQAAqwMAMNQBAACtAwAw1QEAAK4DADALFwAAngMAMBgAAKIDADDNAQAAnwMAMM4BAACgAwAwzwEAAOoCADDQAQAA6gIAMNEBAADqAgAw0gEAAKEDACDTAQAA6gIAMNQBAACjAwAw1QEAAO0CADALFwAAlQMAMBgAAJkDADDNAQAAlgMAMM4BAACXAwAwzwEAAN4CADDQAQAA3gIAMNEBAADeAgAw0gEAAJgDACDTAQAA3gIAMNQBAACaAwAw1QEAAOECADALFwAAiQMAMBgAAI4DADDNAQAAigMAMM4BAACLAwAwzwEAAI0DADDQAQAAjQMAMNEBAACNAwAw0gEAAIwDACDTAQAAjQMAMNQBAACPAwAw1QEAAJADADAHlgEBAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAbEBAQAAAAGyAQEAAAABswEBAAAAAQIAAAAcACAXAACUAwAgAwAAABwAIBcAAJQDACAYAACTAwAgARAAAMkDADAMBgAAjgIAIJMBAACNAgAwlAEAABoAEJUBAACNAgAwlgEBAAAAAZkBQADjAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhsQEBAAAAAbIBAQCGAgAhswEBAIYCACECAAAAHAAgEAAAkwMAIAIAAACRAwAgEAAAkgMAIAuTAQAAkAMAMJQBAACRAwAQlQEAAJADADCWAQEA4gEAIZkBQADjAQAhmgFAAOMBACGbAUAA4wEAIakBAQDiAQAhsQEBAOIBACGyAQEAhgIAIbMBAQCGAgAhC5MBAACQAwAwlAEAAJEDABCVAQAAkAMAMJYBAQDiAQAhmQFAAOMBACGaAUAA4wEAIZsBQADjAQAhqQEBAOIBACGxAQEA4gEAIbIBAQCGAgAhswEBAIYCACEHlgEBAJ0CACGZAUAAngIAIZoBQACeAgAhmwFAAJ4CACGxAQEAnQIAIbIBAQCjAgAhswEBAKMCACEHlgEBAJ0CACGZAUAAngIAIZoBQACeAgAhmwFAAJ4CACGxAQEAnQIAIbIBAQCjAgAhswEBAKMCACEHlgEBAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAbEBAQAAAAGyAQEAAAABswEBAAAAAQkDAAC2AgAgBwAAtQIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAbQBAgAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAECAAAAEAAgFwAAnQMAIAMAAAAQACAXAACdAwAgGAAAnAMAIAEQAADIAwAwAgAAABAAIBAAAJwDACACAAAA4gIAIBAAAJsDACAHlgEBAJ0CACGaAUAAngIAIZsBQACeAgAhtAECALECACG1AQEAowIAIbYBAQCdAgAhtwEBAJ0CACEJAwAAswIAIAcAALICACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG0AQIAsQIAIbUBAQCjAgAhtgEBAJ0CACG3AQEAnQIAIQkDAAC2AgAgBwAAtQIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAbQBAgAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAEIAwAAxAIAIAgAAMYCACCWAQEAAAABmgFAAAAAAZsBQAAAAAG2AQEAAAABuAFAAAAAAboBAAAAugECAgAAAAsAIBcAAKYDACADAAAACwAgFwAApgMAIBgAAKUDACABEAAAxwMAMAIAAAALACAQAAClAwAgAgAAAO4CACAQAACkAwAgBpYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIbYBAQCdAgAhuAFAAJ4CACG6AQAAuwK6ASIIAwAAvAIAIAgAAL4CACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG2AQEAnQIAIbgBQACeAgAhugEAALsCugEiCAMAAMQCACAIAADGAgAglgEBAAAAAZoBQAAAAAGbAUAAAAABtgEBAAAAAbgBQAAAAAG6AQAAALoBAgyWAQEAAAABmgFAAAAAAZsBQAAAAAGnAQEAAAABqAEBAAAAAaoBAQAAAAGrAQEAAAABrAEBAAAAAa0BQAAAAAGuAUAAAAABrwEBAAAAAbABAQAAAAECAAAAFgAgFwAAsgMAIAMAAAAWACAXAACyAwAgGAAAsQMAIAEQAADGAwAwEQYAAI4CACCTAQAAjwIAMJQBAAAUABCVAQAAjwIAMJYBAQAAAAGaAUAA4wEAIZsBQADjAQAhpwEBAOIBACGoAQEA4gEAIakBAQDiAQAhqgEBAIYCACGrAQEAhgIAIawBAQCGAgAhrQFAAJACACGuAUAAkAIAIa8BAQCGAgAhsAEBAIYCACECAAAAFgAgEAAAsQMAIAIAAACvAwAgEAAAsAMAIBCTAQAArgMAMJQBAACvAwAQlQEAAK4DADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGnAQEA4gEAIagBAQDiAQAhqQEBAOIBACGqAQEAhgIAIasBAQCGAgAhrAEBAIYCACGtAUAAkAIAIa4BQACQAgAhrwEBAIYCACGwAQEAhgIAIRCTAQAArgMAMJQBAACvAwAQlQEAAK4DADCWAQEA4gEAIZoBQADjAQAhmwFAAOMBACGnAQEA4gEAIagBAQDiAQAhqQEBAOIBACGqAQEAhgIAIasBAQCGAgAhrAEBAIYCACGtAUAAkAIAIa4BQACQAgAhrwEBAIYCACGwAQEAhgIAIQyWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGnAQEAnQIAIagBAQCdAgAhqgEBAKMCACGrAQEAowIAIawBAQCjAgAhrQFAAKQCACGuAUAApAIAIa8BAQCjAgAhsAEBAKMCACEMlgEBAJ0CACGaAUAAngIAIZsBQACeAgAhpwEBAJ0CACGoAQEAnQIAIaoBAQCjAgAhqwEBAKMCACGsAQEAowIAIa0BQACkAgAhrgFAAKQCACGvAQEAowIAIbABAQCjAgAhDJYBAQAAAAGaAUAAAAABmwFAAAAAAacBAQAAAAGoAQEAAAABqgEBAAAAAasBAQAAAAGsAQEAAAABrQFAAAAAAa4BQAAAAAGvAQEAAAABsAEBAAAAAQsFAAD-AgAgBwAA9AIAIAgAAPUCACCWAQEAAAABmgFAAAAAAZsBQAAAAAG_AQEAAAABwAECAAAAAcEBAgAAAAHCASAAAAABwwEBAAAAAQIAAAAGACAXAACzAwAgAwAAAAMAIBcAALMDACAYAAC3AwAgDQAAAAMAIAUAAP0CACAHAADYAgAgCAAA2QIAIBAAALcDACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG_AQEAowIAIcABAgCxAgAhwQECALECACHCASAA1QIAIcMBAQCdAgAhCwUAAP0CACAHAADYAgAgCAAA2QIAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIb8BAQCjAgAhwAECALECACHBAQIAsQIAIcIBIADVAgAhwwEBAJ0CACEDFwAAswMAIM0BAAC0AwAg0QEAAAYAIAQXAACnAwAwzQEAAKgDADDRAQAAqwMAMNIBAACqAwAgBBcAAJ4DADDNAQAAnwMAMNEBAADqAgAw0gEAAKEDACAEFwAAlQMAMM0BAACWAwAw0QEAAN4CADDSAQAAmAMAIAQXAACJAwAwzQEAAIoDADDRAQAAjQMAMNIBAACMAwAgBQUAAMUDACAGAADCAwAgBwAAvwMAIAgAAMADACC_AQAAnwIAIAAAAAAHAwAAvQMAIAcAAL8DACAIAADAAwAgCQAAvgMAIAoAAMEDACDIAQAAnwIAIMkBAACfAgAgAwMAAL0DACAGAADCAwAgCAAAxAMAIAQDAAC9AwAgBgAAwgMAIAcAAMMDACC1AQAAnwIAIAEDAAD3AgAgDJYBAQAAAAGaAUAAAAABmwFAAAAAAacBAQAAAAGoAQEAAAABqgEBAAAAAasBAQAAAAGsAQEAAAABrQFAAAAAAa4BQAAAAAGvAQEAAAABsAEBAAAAAQaWAQEAAAABmgFAAAAAAZsBQAAAAAG2AQEAAAABuAFAAAAAAboBAAAAugECB5YBAQAAAAGaAUAAAAABmwFAAAAAAbQBAgAAAAG1AQEAAAABtgEBAAAAAbcBAQAAAAEHlgEBAAAAAZkBQAAAAAGaAUAAAAABmwFAAAAAAbEBAQAAAAGyAQEAAAABswEBAAAAAQKWAQEAAAABuwEBAAAAAQIAAABPACAXAADKAwAgAwAAAFIAIBcAAMoDACAYAADOAwAgBAAAAFIAIBAAAM4DACCWAQEAnQIAIbsBAQCdAgAhApYBAQCdAgAhuwEBAJ0CACEOBwAAugMAIAgAALsDACAJAAC5AwAgCgAAvAMAIJYBAQAAAAGaAUAAAAABmwFAAAAAAboBAAAAywECuwEBAAAAAcQBAQAAAAHFASAAAAABxwEAAADHAQLIAQEAAAAByQEBAAAAAQIAAAABACAXAADPAwAgBpYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG4AUAAAAABugEAAAC6AQIHlgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAbQBAgAAAAG1AQEAAAABtwEBAAAAAQMAAAAjACAXAADPAwAgGAAA1QMAIBAAAAAjACAHAACGAwAgCAAAhwMAIAkAAIUDACAKAACIAwAgEAAA1QMAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIboBAACDA8sBIrsBAQCdAgAhxAEBAJ0CACHFASAA1QIAIccBAACCA8cBIsgBAQCjAgAhyQEBAKMCACEOBwAAhgMAIAgAAIcDACAJAACFAwAgCgAAiAMAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIboBAACDA8sBIrsBAQCdAgAhxAEBAJ0CACHFASAA1QIAIccBAACCA8cBIsgBAQCjAgAhyQEBAKMCACEIlgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAb8BAQAAAAHAAQIAAAABwQECAAAAAcIBIAAAAAEOAwAAuAMAIAgAALsDACAJAAC5AwAgCgAAvAMAIJYBAQAAAAGaAUAAAAABmwFAAAAAAboBAAAAywECuwEBAAAAAcQBAQAAAAHFASAAAAABxwEAAADHAQLIAQEAAAAByQEBAAAAAQIAAAABACAXAADXAwAgDAUAAP4CACAGAADzAgAgCAAA9QIAIJYBAQAAAAGaAUAAAAABmwFAAAAAAakBAQAAAAG_AQEAAAABwAECAAAAAcEBAgAAAAHCASAAAAABwwEBAAAAAQIAAAAGACAXAADZAwAgAwAAACMAIBcAANcDACAYAADdAwAgEAAAACMAIAMAAIQDACAIAACHAwAgCQAAhQMAIAoAAIgDACAQAADdAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQ4DAACEAwAgCAAAhwMAIAkAAIUDACAKAACIAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQMAAAADACAXAADZAwAgGAAA4AMAIA4AAAADACAFAAD9AgAgBgAA1wIAIAgAANkCACAQAADgAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhqQEBAJ0CACG_AQEAowIAIcABAgCxAgAhwQECALECACHCASAA1QIAIcMBAQCdAgAhDAUAAP0CACAGAADXAgAgCAAA2QIAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhvwEBAKMCACHAAQIAsQIAIcEBAgCxAgAhwgEgANUCACHDAQEAnQIAIQ4DAAC4AwAgBwAAugMAIAkAALkDACAKAAC8AwAglgEBAAAAAZoBQAAAAAGbAUAAAAABugEAAADLAQK7AQEAAAABxAEBAAAAAcUBIAAAAAHHAQAAAMcBAsgBAQAAAAHJAQEAAAABAgAAAAEAIBcAAOEDACAMBQAA_gIAIAYAAPMCACAHAAD0AgAglgEBAAAAAZoBQAAAAAGbAUAAAAABqQEBAAAAAb8BAQAAAAHAAQIAAAABwQECAAAAAcIBIAAAAAHDAQEAAAABAgAAAAYAIBcAAOMDACAJAwAAxAIAIAYAAMUCACCWAQEAAAABmgFAAAAAAZsBQAAAAAGpAQEAAAABtgEBAAAAAbgBQAAAAAG6AQAAALoBAgIAAAALACAXAADlAwAgAwAAACMAIBcAAOEDACAYAADpAwAgEAAAACMAIAMAAIQDACAHAACGAwAgCQAAhQMAIAoAAIgDACAQAADpAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQ4DAACEAwAgBwAAhgMAIAkAAIUDACAKAACIAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQMAAAADACAXAADjAwAgGAAA7AMAIA4AAAADACAFAAD9AgAgBgAA1wIAIAcAANgCACAQAADsAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhqQEBAJ0CACG_AQEAowIAIcABAgCxAgAhwQECALECACHCASAA1QIAIcMBAQCdAgAhDAUAAP0CACAGAADXAgAgBwAA2AIAIJYBAQCdAgAhmgFAAJ4CACGbAUAAngIAIakBAQCdAgAhvwEBAKMCACHAAQIAsQIAIcEBAgCxAgAhwgEgANUCACHDAQEAnQIAIQMAAAAJACAXAADlAwAgGAAA7wMAIAsAAAAJACADAAC8AgAgBgAAvQIAIBAAAO8DACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbYBAQCdAgAhuAFAAJ4CACG6AQAAuwK6ASIJAwAAvAIAIAYAAL0CACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACGpAQEAnQIAIbYBAQCdAgAhuAFAAJ4CACG6AQAAuwK6ASIOAwAAuAMAIAcAALoDACAIAAC7AwAgCQAAuQMAIJYBAQAAAAGaAUAAAAABmwFAAAAAAboBAAAAywECuwEBAAAAAcQBAQAAAAHFASAAAAABxwEAAADHAQLIAQEAAAAByQEBAAAAAQIAAAABACAXAADwAwAgAwAAACMAIBcAAPADACAYAAD0AwAgEAAAACMAIAMAAIQDACAHAACGAwAgCAAAhwMAIAkAAIUDACAQAAD0AwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQ4DAACEAwAgBwAAhgMAIAgAAIcDACAJAACFAwAglgEBAJ0CACGaAUAAngIAIZsBQACeAgAhugEAAIMDywEiuwEBAJ0CACHEAQEAnQIAIcUBIADVAgAhxwEAAIIDxwEiyAEBAKMCACHJAQEAowIAIQ4DAAC4AwAgBwAAugMAIAgAALsDACAKAAC8AwAglgEBAAAAAZoBQAAAAAGbAUAAAAABugEAAADLAQK7AQEAAAABxAEBAAAAAcUBIAAAAAHHAQAAAMcBAsgBAQAAAAHJAQEAAAABAgAAAAEAIBcAAPUDACADAAAAIwAgFwAA9QMAIBgAAPkDACAQAAAAIwAgAwAAhAMAIAcAAIYDACAIAACHAwAgCgAAiAMAIBAAAPkDACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG6AQAAgwPLASK7AQEAnQIAIcQBAQCdAgAhxQEgANUCACHHAQAAggPHASLIAQEAowIAIckBAQCjAgAhDgMAAIQDACAHAACGAwAgCAAAhwMAIAoAAIgDACCWAQEAnQIAIZoBQACeAgAhmwFAAJ4CACG6AQAAgwPLASK7AQEAnQIAIcQBAQCdAgAhxQEgANUCACHHAQAAggPHASLIAQEAowIAIckBAQCjAgAhBgMEAgQACgcYBQgZBgkXCAodCQUEAAcFAAMGAAEHDAUIEQYCAwcCBAAEAQMIAAMDAAIGAAEIDgYDAwACBgABBwAFAgcSAAgTAAEGAAEBBgABBAcfAAggAAkeAAohAAAAAAMEAA8dABAeABEAAAADBAAPHQAQHgARAgUAAwYAAQIFAAMGAAEFBAAWHQAZHgAaLwAXMAAYAAAAAAAFBAAWHQAZHgAaLwAXMAAYAAADBAAfHQAgHgAhAAAAAwQAHx0AIB4AIQIDAAIGAAECAwACBgABAwQAJh0AJx4AKAAAAAMEACYdACceACgDAwACBgABBwAFAwMAAgYAAQcABQUEAC0dADAeADEvAC4wAC8AAAAAAAUEAC0dADAeADEvAC4wAC8BBgABAQYAAQMEADYdADceADgAAAADBAA2HQA3HgA4AQYAAQEGAAEDBAA9HQA-HgA_AAAAAwQAPR0APh4APwAAAAMEAEUdAEYeAEcAAAADBABFHQBGHgBHCwIBDCIBDSUBDiYBDycBESkBEisLEywMFC4BFTALFjENGTIBGjMBGzQLHzcOIDgSITkCIjoCIzsCJDwCJT0CJj8CJ0ELKEITKUQCKkYLK0cULEgCLUkCLkoLMU0VMk4bM1ADNFEDNVQDNlUDN1YDOFgDOVoLOlscO10DPF8LPWAdPmEDP2IDQGMLQWYeQmciQ2gFRGkFRWoFRmsFR2wFSG4FSXALSnEjS3MFTHULTXYkTncFT3gFUHkLUXwlUn0pU34GVH8GVYABBlaBAQZXggEGWIQBBlmGAQtahwEqW4kBBlyLAQtdjAErXo0BBl-OAQZgjwELYZIBLGKTATJjlAEJZJUBCWWWAQlmlwEJZ5gBCWiaAQlpnAELap0BM2ufAQlsoQELbaIBNG6jAQlvpAEJcKUBC3GoATVyqQE5c6oBCHSrAQh1rAEIdq0BCHeuAQh4sAEIebIBC3qzATp7tQEIfLcBC324ATt-uQEIf7oBCIABuwELgQG-ATyCAb8BQIMBwQFBhAHCAUGFAcUBQYYBxgFBhwHHAUGIAckBQYkBywELigHMAUKLAc4BQYwB0AELjQHRAUOOAdIBQY8B0wFBkAHUAQuRAdcBRJIB2AFI"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer } = await import("buffer");
  const wasmArray = Buffer.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
import * as runtime2 from "@prisma/client/runtime/client";
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/lib/auth.ts
var auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "postgresql"
    // or "mysql", "postgresql", ...etc
  }),
  trustedOrigins: [process.env.APP_URL],
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: false,
    autoLoginAfterRegister: false
  },
  user: {
    additionalFields: {
      role: {
        type: "string",
        required: false,
        defaultValue: "STUDENT"
      },
      status: {
        type: "string",
        defaultValue: "ACTIVE",
        required: false
      },
      phone: {
        type: "string",
        required: false
      }
    }
  }
});

// src/app.ts
import cors from "cors";

// src/modules/booking/booking.router.ts
import { Router } from "express";

// src/modules/booking/booking.service.ts
var createBooking = async (payload, userId) => {
  const existTutorProfile = await prisma.tutorProfile.findUnique({
    where: {
      id: payload.tutorId
    }
  });
  const activeBookingCount = await prisma.booking.count({
    where: {
      userId,
      tutorId: payload.tutorId,
      status: {
        in: ["PENDING", "CONFIRMED"]
      }
    }
  });
  if (activeBookingCount > 0) {
    throw new Error("You already have an active booking");
  }
  if (!existTutorProfile) {
    throw new Error("Tutor profile not exist!!");
  }
  if (existTutorProfile && !existTutorProfile.availablity) {
    throw new Error("Tutor not available right now");
  }
  const result = await prisma.booking.create({
    data: {
      ...payload,
      userId
    }
  });
  return result;
};
var getBooking = async (payload, userId, role) => {
  let booking = [];
  let totalBooking = 0;
  if (role === "STUDENT") {
    booking = await prisma.booking.findMany({
      where: {
        userId
      },
      include: {
        tutor: true,
        review: true
      },
      skip: payload.skip,
      take: payload.limit
    });
    totalBooking = await prisma.booking.count({
      where: {
        userId
      }
    });
  }
  if (role === "TUTOR") {
    const tutorProfile = await prisma.tutorProfile.findUnique({
      where: {
        userId
      }
    });
    if (!tutorProfile) {
      throw new Error("Tutor profile not found so no booking here");
    }
    booking = await prisma.booking.findMany({
      where: {
        tutorId: tutorProfile.id,
        status: {
          in: ["PENDING", "CONFIRMED", "COMPLETED"]
        }
      },
      include: {
        user: true
      },
      skip: payload.skip,
      take: payload.limit
    });
    totalBooking = await prisma.booking.count({
      where: {
        tutorId: tutorProfile.id
      }
    });
  }
  if (role === "ADMIN") {
    booking = await prisma.booking.findMany({
      include: {
        tutor: true,
        user: true
      },
      skip: payload.skip,
      take: payload.limit
    });
    totalBooking = await prisma.booking.count();
  }
  const formattedBookings = booking.map((b) => {
    return {
      id: b.id,
      status: b.status,
      user: b.user,
      tutor: b.tutor,
      review: b.review,
      createdAt: b.createdAt,
      updatedAt: b.updatedAt
    };
  });
  return {
    data: formattedBookings,
    paginations: {
      totalBooking,
      page: payload.page,
      limit: payload.limit,
      totalPage: Math.ceil(totalBooking / payload.limit)
    }
  };
};
var getBookingById = async (userId, bookingId, role) => {
  const existBooking = await prisma.booking.findUnique({
    where: {
      id: bookingId
    }
  });
  if (!existBooking) {
    throw new Error("Booking not found");
  }
  if (role === "STUDENT") {
    return await prisma.booking.findFirst({
      where: {
        id: existBooking.id,
        userId
      },
      include: {
        tutor: true
      }
    });
  }
  if (role === "TUTOR") {
    const tutorProfile = await prisma.tutorProfile.findUnique({
      where: {
        userId
      }
    });
    if (!tutorProfile) {
      throw new Error("Tutor profile not found");
    }
    return await prisma.booking.findFirst({
      where: {
        id: existBooking.id,
        tutorId: tutorProfile.id
      },
      include: {
        user: true
      }
    });
  }
  if (role === "ADMIN") {
    return await prisma.booking.findUnique({
      where: {
        id: existBooking.id
      },
      include: {
        tutor: true,
        user: true
      }
    });
  }
  throw new Error("Invalid role provided");
};
var cancelBooking = async (userId, bookingId) => {
  const bookingData = await prisma.booking.findFirst({
    where: {
      id: bookingId,
      userId
    }
  });
  if (!bookingData) {
    throw new Error("Booking not found");
  }
  if (bookingData.status !== "PENDING") {
    throw new Error("You can only cancel pending booking");
  }
  return await prisma.booking.update({
    where: {
      id: bookingData.id
    },
    data: {
      status: "CANCELLED"
    }
  });
};
var updateBooking = async (payload, tutorId, bookingId) => {
  const existTutorProfile = await prisma.tutorProfile.findFirst({
    where: {
      userId: tutorId
    }
  });
  if (!existTutorProfile) {
    throw new Error("Tutor profile not found");
  }
  const bookingData = await prisma.booking.findUnique({
    where: {
      id: bookingId
    }
  });
  if (!bookingData) {
    throw new Error("Booking not found");
  }
  if (bookingData.tutorId !== existTutorProfile.id) {
    throw new Error("You cann't access this part");
  }
  return await prisma.booking.update({
    where: {
      id: bookingData.id
    },
    data: {
      ...payload
    }
  });
};
var bookingService = {
  createBooking,
  getBooking,
  getBookingById,
  updateBooking,
  cancelBooking
};

// src/helpers/paginationSortHelpers.ts
var paginationSortHelpers = (options) => {
  const page = Number(options.page || 1);
  const limit = Number(options.limit || 10);
  const skip = (page - 1) * limit;
  const sortBy = options.sortBy || "createdAt";
  const sortOrder = options.sortOrder || "desc";
  return {
    page,
    limit,
    skip,
    sortBy,
    sortOrder
  };
};
var paginationSortHelpers_default = paginationSortHelpers;

// src/modules/booking/booking.controller.ts
var createBooking2 = async (req, res) => {
  try {
    const user = req.user;
    if (!user) {
      res.status(403).json({
        message: "You are Unauthorized!!!"
      });
    }
    const result = await bookingService.createBooking(
      req.body,
      user?.id
    );
    res.status(201).json({
      message: "Booking Created Successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var getBooking2 = async (req, res) => {
  try {
    const user = req.user;
    console.log(user);
    const { page, limit, skip, sortBy, sortOrder } = paginationSortHelpers_default(
      req.query
    );
    const result = await bookingService.getBooking(
      { page, limit, skip, sortBy, sortOrder },
      user?.id,
      user?.role
    );
    res.status(201).json({
      message: "Booking fetched successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var getBookingById2 = async (req, res) => {
  try {
    const user = req.user;
    const bookingId = req.params.bookingId;
    const result = await bookingService.getBookingById(
      user?.id,
      bookingId,
      user?.role
    );
    res.status(201).json({
      message: "Booking Fetched successfully by id",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var cancelBooking2 = async (req, res) => {
  try {
    const user = req.user;
    const bookingId = req.params.bookingId;
    const result = await bookingService.cancelBooking(
      user?.id,
      bookingId
    );
    res.status(201).json({
      message: "Booking cancelled successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var updateBooking2 = async (req, res) => {
  try {
    const user = req.user;
    const bookingId = req.params.bookingId;
    const result = await bookingService.updateBooking(
      req.body,
      user?.id,
      bookingId
    );
    res.status(201).json({
      message: "Booking upadated successfully by tutor",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var bookingController = {
  createBooking: createBooking2,
  getBooking: getBooking2,
  getBookingById: getBookingById2,
  updateBooking: updateBooking2,
  cancelBooking: cancelBooking2
};

// src/middlewares/auth.ts
var auth2 = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      console.log(session?.user);
      if (!session) {
        return res.status(401).json({
          success: false,
          message: "You are unauthorized!!!"
        });
      }
      if (!session?.user.emailVerified) {
        return res.status(403).json({
          success: false,
          message: "Plz verify your email"
        });
      }
      req.user = {
        id: session?.user.id,
        name: session?.user.name,
        email: session?.user.email,
        role: session?.user.role,
        emailVerify: session?.user.emailVerified
      };
      if (roles.length && !roles.includes(req.user.role)) {
        return res.status(403).json({
          success: false,
          message: "you don't have permission to acces this part"
        });
      }
      next();
    } catch (error) {
      next(error);
    }
  };
};
var auth_default = auth2;

// src/modules/booking/booking.router.ts
var router = Router();
router.post("/", auth_default("STUDENT" /* STUDENT */), bookingController.createBooking);
router.get(
  "/",
  auth_default("STUDENT" /* STUDENT */, "TUTOR" /* TUTOR */, "ADMIN" /* ADMIN */),
  bookingController.getBooking
);
router.get(
  "/:bookingId",
  auth_default("STUDENT" /* STUDENT */, "TUTOR" /* TUTOR */, "ADMIN" /* ADMIN */),
  bookingController.getBookingById
);
router.patch(
  "/:bookingId/cancel",
  auth_default("STUDENT" /* STUDENT */),
  bookingController.cancelBooking
);
router.patch(
  "/:bookingId/status",
  auth_default("TUTOR" /* TUTOR */),
  bookingController.updateBooking
);
var bookingRouter = router;

// src/modules/category/category.router.ts
import { Router as Router2 } from "express";

// src/modules/category/category.service.ts
var createCategory = async (payload) => {
  console.log("payload", payload);
  const result = await prisma.category.create({
    data: {
      ...payload
    }
  });
  return result;
};
var getCategory = async () => {
  const result = await prisma.category.findMany();
  return result;
};
var getCategoryById = async (categoryId) => {
  const existCategory = await prisma.category.findUnique({
    where: {
      id: categoryId
    }
  });
  if (!existCategory) {
    throw new Error("Category not found");
  }
  return await prisma.category.findFirst({
    where: {
      id: existCategory.id
    }
  });
};
var updateCategory = async (payload, categoryId) => {
  const existCategory = await prisma.category.findUnique({
    where: {
      id: categoryId
    }
  });
  const existTutor = await prisma.tutorProfile.findFirst({
    where: {
      categoryId
    }
  });
  if (!existCategory) {
    throw new Error("Category not found");
  }
  if (existTutor) {
    throw new Error("You Cannot update category with assigned tutors");
  }
  return await prisma.category.update({
    where: {
      id: categoryId
    },
    data: {
      ...payload
    }
  });
};
var deleteCategory = async (categoryId) => {
  const existCategory = await prisma.category.findUnique({
    where: {
      id: categoryId
    }
  });
  const existTutor = await prisma.tutorProfile.findFirst({
    where: {
      categoryId
    }
  });
  if (!existCategory) {
    throw new Error("Category not found");
  }
  if (existTutor) {
    throw new Error("You Cannot delete category with assigned tutors");
  }
  return await prisma.category.delete({
    where: {
      id: categoryId
    }
  });
};
var categoryService = {
  createCategory,
  getCategory,
  getCategoryById,
  updateCategory,
  deleteCategory
};

// src/modules/category/category.controller.ts
var createCategory2 = async (req, res) => {
  console.log("body", req.body);
  const result = await categoryService.createCategory(req.body);
  res.status(201).json({
    message: "Category Created successfully",
    data: result
  });
};
var getCategory2 = async (req, res) => {
  const result = await categoryService.getCategory();
  res.status(201).json({
    message: "Category fetched successfully",
    data: result
  });
  return result;
};
var getCategoryById2 = async (req, res) => {
  try {
    const categoryId = req.params.categoryId;
    const result = await categoryService.getCategoryById(categoryId);
    res.status(201).json({
      message: "Category fetched successfully by Id",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var updateCategory2 = async (req, res) => {
  try {
    const categoryId = req.params.categoryId;
    const result = await categoryService.updateCategory(
      req.body,
      categoryId
    );
    res.status(201).json({
      message: "Category updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var deleteCategory2 = async (req, res) => {
  try {
    const categoryId = req.params.categoryId;
    const result = await categoryService.deleteCategory(categoryId);
    res.status(201).json({
      message: "Category deleted successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var categoryController = {
  createCategory: createCategory2,
  getCategory: getCategory2,
  getCategoryById: getCategoryById2,
  updateCategory: updateCategory2,
  deleteCategory: deleteCategory2
};

// src/modules/category/category.router.ts
var router2 = Router2();
router2.post("/", auth_default("ADMIN" /* ADMIN */), categoryController.createCategory);
router2.get("/", categoryController.getCategory);
router2.get("/:categoryId", categoryController.getCategoryById);
router2.patch(
  "/:categoryId",
  auth_default("ADMIN" /* ADMIN */),
  categoryController.updateCategory
);
router2.delete(
  "/:categoryId",
  auth_default("ADMIN" /* ADMIN */),
  categoryController.deleteCategory
);
var categoryRouter = router2;

// src/modules/tutor/tutor.router.ts
import { Router as Router3 } from "express";

// src/modules/tutor/tutor.service.ts
var createTutor = async (payload, userId) => {
  const existingTutor = await prisma.tutorProfile.findUnique({
    where: {
      userId
    }
  });
  if (existingTutor) {
    throw new Error("Tutor profile already exits!!!");
  }
  const result = await prisma.tutorProfile.create({
    data: {
      ...payload,
      userId
    }
  });
  return result;
};
var getTutor = async (payload) => {
  const allAndConditions = [];
  if (payload.search) {
    allAndConditions.push({
      category: {
        is: {
          name: {
            contains: payload.search,
            mode: "insensitive"
          }
        }
      }
    });
  }
  const tutors = await prisma.tutorProfile.findMany({
    take: payload.limit,
    skip: payload.skip,
    where: {
      AND: allAndConditions
    },
    orderBy: payload.sortBy && payload.sortOrder ? {
      [payload.sortBy]: payload.sortOrder
    } : { createdAt: "desc" },
    include: {
      category: true,
      user: true,
      _count: {
        select: {
          booking: true,
          review: true
        }
      },
      review: {
        select: {
          rating: true
        }
      }
    }
  });
  const formattedTutors = tutors.map((tutor) => {
    const totalReview = tutor.review.length;
    const averageRating = totalReview > 0 ? Number(
      tutor.review.reduce((acc, r) => acc + r.rating, 0) / totalReview
    ) : 0;
    return {
      id: tutor.id,
      bio: tutor.bio,
      category: tutor.category,
      user: tutor.user,
      totalBookings: tutor._count.booking,
      totalReview,
      averageRating
    };
  });
  const total = await prisma.tutorProfile.count({
    where: {
      AND: allAndConditions
    }
  });
  return {
    data: formattedTutors,
    paginations: {
      total,
      page: payload.page,
      limit: payload.limit,
      totalPage: Math.ceil(total / payload.limit)
    }
  };
};
var getTutorById = async (tutorId) => {
  const tutor = await prisma.tutorProfile.findUnique({
    where: {
      id: tutorId
    },
    include: {
      category: true,
      user: true,
      _count: {
        select: {
          booking: true,
          review: true
        }
      },
      review: {
        select: {
          rating: true
        }
      }
    }
  });
  if (!tutor) {
    throw new Error("Tutor not found");
  }
  const totalReview = tutor.review.length;
  const averageRating = totalReview > 0 ? Number(tutor.review.reduce((acc, r) => acc + r.rating, 0) / totalReview) : 0;
  const formattedTutor = {
    id: tutor.id,
    bio: tutor.bio,
    category: tutor.category,
    user: tutor.user,
    totalBookings: tutor._count.booking,
    totalReview,
    averageRating
  };
  return formattedTutor;
};
var updateTutor = async (payload, userId, tutorId) => {
  const tutorProfileData = await prisma.tutorProfile.findUnique({
    where: {
      id: tutorId
    }
  });
  console.log(tutorProfileData);
  if (!tutorProfileData) {
    throw new Error("Tutor not found");
  }
  if (tutorProfileData.userId !== userId) {
    throw new Error("You are not allowed to access this part");
  }
  return await prisma.tutorProfile.update({
    where: {
      id: tutorProfileData.id
    },
    data: {
      ...payload
    }
  });
};
var deleteTutor = async (tutorId) => {
  const existBooking = await prisma.booking.findFirst({
    where: {
      tutorId
    }
  });
  if (existBooking) {
    throw new Error("You cann't delete tutor with existing bookings");
  }
  return await prisma.tutorProfile.delete({
    where: {
      id: tutorId
    }
  });
};
var tutorService = {
  createTutor,
  getTutor,
  getTutorById,
  updateTutor,
  deleteTutor
};

// src/modules/tutor/tutor.controller.ts
var createTutor2 = async (req, res) => {
  try {
    const user = req.user;
    if (!user) {
      return res.status(403).json({
        message: "You ar unauthorized!!"
      });
    }
    const result = await tutorService.createTutor(req.body, user?.id);
    res.status(201).json({
      message: "Tutor Profile Created Successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var getTutor2 = async (req, res) => {
  try {
    const search = typeof req.query.search === "string" ? req.query.search : void 0;
    const { page, limit, skip, sortBy, sortOrder } = paginationSortHelpers_default(
      req.query
    );
    const result = await tutorService.getTutor({
      search,
      page,
      limit,
      skip,
      sortBy,
      sortOrder
    });
    res.status(201).json({
      message: "Tutor fetched successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var getTutorById2 = async (req, res) => {
  try {
    const tutorId = req.params.tutorId;
    const result = await tutorService.getTutorById(tutorId);
    res.status(201).json({
      message: "Tutor Fetched successfully by Id",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var updateTutor2 = async (req, res) => {
  try {
    const tutorId = req.params.tutorId;
    const user = req.user;
    if (!user) {
      res.status(403).json({
        message: "You are unauthorized"
      });
    }
    const result = await tutorService.updateTutor(
      req.body,
      user?.id,
      tutorId
    );
    res.status(201).json({
      message: "Tutor updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var deleteTutor2 = async (req, res) => {
  try {
    const tutorId = req.params.tutorId;
    const result = await tutorService.deleteTutor(tutorId);
    res.status(201).json({
      message: "Tutor updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var tutorController = {
  createTutor: createTutor2,
  getTutor: getTutor2,
  getTutorById: getTutorById2,
  updateTutor: updateTutor2,
  deleteTutor: deleteTutor2
};

// src/modules/tutor/tutor.router.ts
var router3 = Router3();
router3.post("/", auth_default("TUTOR" /* TUTOR */), tutorController.createTutor);
router3.get("/", tutorController.getTutor);
router3.get("/:tutorId", tutorController.getTutorById);
router3.put("/:tutorId", auth_default("TUTOR" /* TUTOR */), tutorController.updateTutor);
router3.delete("/:tutorId", auth_default("ADMIN" /* ADMIN */), tutorController.deleteTutor);
var tutorRouter = router3;

// src/modules/review/review.router.ts
import { Router as Router4 } from "express";

// src/modules/review/review.service.ts
var createReview = async (payload, userId) => {
  const existBooking = await prisma.booking.findFirst({
    where: {
      id: payload.bookingId
    }
  });
  const alreadyReviewed = await prisma.review.findUnique({
    where: {
      bookingId: payload.bookingId
    }
  });
  if (alreadyReviewed) {
    throw new Error(
      "You cann't reviewed again because you already reviewed this session"
    );
  }
  if (!existBooking) {
    throw new Error("Booking not found");
  }
  if (existBooking.status !== "COMPLETED") {
    throw new Error(
      "You cann't review this tutor because session is not completed"
    );
  }
  if (existBooking.userId !== userId || existBooking.tutorId !== payload.tutorId) {
    throw new Error("You cann't review this tutor because he is not your tutor");
  }
  const result = await prisma.review.create({
    data: {
      ...payload,
      userId
    }
  });
  return result;
};
var getReview = async () => {
  const result = await prisma.review.findMany();
  return result;
};
var getReviewById = async (reviewId) => {
  const result = await prisma.review.findUnique({
    where: {
      id: reviewId
    }
  });
  return result;
};
var updateReview = async (payload, userId, reviewId) => {
  const existReview = await prisma.review.findUnique({
    where: {
      id: reviewId
    }
  });
  if (!existReview) {
    throw new Error("You don't reviewed any tutor!!");
  }
  if (existReview.userId !== userId) {
    throw new Error("You are not allowed to update this review");
  }
  const updateReview3 = await prisma.review.update({
    where: {
      id: reviewId
    },
    data: {
      ...payload
    }
  });
  return updateReview3;
};
var deleteReview = async (payload, userId, reviewId, role) => {
  const existReview = await prisma.review.findUnique({
    where: {
      id: reviewId
    }
  });
  if (!existReview) {
    throw new Error("Review not found!!");
  }
  if (role === "STUDENT" && existReview.userId !== userId) {
    throw new Error("You can delete only your own review");
  }
  return await prisma.review.delete({
    where: {
      id: reviewId
    }
  });
};
var reviewService = {
  createReview,
  getReview,
  updateReview,
  getReviewById,
  deleteReview
};

// src/modules/review/review.controller.ts
var createReview2 = async (req, res) => {
  try {
    const user = req.user;
    if (!user) {
      res.status(403).json({
        message: "You ar unauthorized!!"
      });
    }
    const result = await reviewService.createReview(
      req.body,
      user?.id
    );
    res.status(201).json({
      message: "Review Created successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var getReview2 = async (req, res) => {
  const result = await reviewService.getReview();
  res.status(201).json({
    message: "Review fetched successfully",
    data: result
  });
};
var getReviewById2 = async (req, res) => {
  try {
    const reviewId = req.params.reviewId;
    const result = await reviewService.getReviewById(reviewId);
    res.status(201).json({
      message: "Review fetched successfully by id",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var updateReview2 = async (req, res) => {
  try {
    const user = req.user;
    const reviewId = req.params.reviewId;
    const result = await reviewService.updateReview(
      req.body,
      user?.id,
      reviewId
    );
    res.status(201).json({
      message: "Review updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var deleteReview2 = async (req, res) => {
  try {
    const user = req.user;
    const reviewId = req.params.reviewId;
    const result = await reviewService.deleteReview(
      req.body,
      user?.id,
      reviewId,
      user?.role
    );
    res.status(201).json({
      message: "Review updated successfully",
      data: result
    });
  } catch (error) {
    res.status(404).json({
      success: false,
      message: error.message || "Something went wrong"
    });
  }
};
var reviewController = {
  createReview: createReview2,
  getReview: getReview2,
  updateReview: updateReview2,
  getReviewById: getReviewById2,
  deleteReview: deleteReview2
};

// src/modules/review/review.router.ts
var router4 = Router4();
router4.post("/", auth_default("STUDENT" /* STUDENT */), reviewController.createReview);
router4.get("/", reviewController.getReview);
router4.get("/:reviewId", reviewController.getReviewById);
router4.patch(
  "/:reviewId",
  auth_default("STUDENT" /* STUDENT */),
  reviewController.updateReview
);
router4.delete(
  "/:reviewId",
  auth_default("STUDENT" /* STUDENT */, "ADMIN" /* ADMIN */),
  reviewController.deleteReview
);
var reviewRouter = router4;

// src/app.ts
var app = express();
var allowedOrigins = [
  process.env.APP_URL || "http://localhost:3000"
].filter(Boolean);
app.use(
  cors({
    origin: (origin, callback) => {
      if (!origin) return callback(null, true);
      const isAllowed = allowedOrigins.includes(origin) || /^https:\/\/next-blog-client.*\.vercel\.app$/.test(origin) || /^https:\/\/.*\.vercel\.app$/.test(origin);
      if (isAllowed) {
        callback(null, true);
      } else {
        callback(new Error(`Origin ${origin} not allowed by CORS`));
      }
    },
    credentials: true,
    methods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
    allowedHeaders: ["Content-Type", "Authorization", "Cookie"],
    exposedHeaders: ["Set-Cookie"]
  })
);
app.use(express.json());
app.all("/api/auth/*splat", toNodeHandler(auth));
app.use("/api/tutors", tutorRouter);
app.use("/api/bookings", bookingRouter);
app.use("/api/categories", categoryRouter);
app.use("/api/reviews", reviewRouter);
app.get("/", (req, res) => {
  res.send("Hello Skill Bridge Backend!!!");
});
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
